apiVersion: apps/v1
kind: Deployment
metadata:
  name: a2a-agent
  namespace: a2a-demo
  labels:
    app: a2a-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: a2a-agent
  template:
    metadata:
      labels:
        app: a2a-agent
    spec:
      containers:
        - name: a2a-agent
          image: localhost:5001/a2a-cloud-deployment:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: agent-config
                  key: DATABASE_URL
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: agent-config
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: agent-config
                  key: DATABASE_PASSWORD
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: agent-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: AGENT_URL
              valueFrom:
                configMapKeyRef:
                  name: agent-config
                  key: AGENT_URL
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: a2a-agent-service
  namespace: a2a-demo
spec:
  selector:
    app: a2a-agent
  ports:
    - protocol: TCP
      port: 8080        # Service port inside cluster
      targetPort: 8080  # Pod port
      nodePort: 30080   # Fixed NodePort (mapped to host port 8080 via Kind config)
  type: NodePort
  sessionAffinity: None  # Ensures round-robin load balancing
