// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package org.a2aproject.sdk.compat03.grpc;

@com.google.protobuf.Generated
public interface OAuthFlowsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.OAuthFlows)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1;</code>
   * @return Whether the authorizationCode field is set.
   */
  boolean hasAuthorizationCode();
  /**
   * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1;</code>
   * @return The authorizationCode.
   */
  org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlow getAuthorizationCode();
  /**
   * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1;</code>
   */
  org.a2aproject.sdk.compat03.grpc.AuthorizationCodeOAuthFlowOrBuilder getAuthorizationCodeOrBuilder();

  /**
   * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2;</code>
   * @return Whether the clientCredentials field is set.
   */
  boolean hasClientCredentials();
  /**
   * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2;</code>
   * @return The clientCredentials.
   */
  org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlow getClientCredentials();
  /**
   * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2;</code>
   */
  org.a2aproject.sdk.compat03.grpc.ClientCredentialsOAuthFlowOrBuilder getClientCredentialsOrBuilder();

  /**
   * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3;</code>
   * @return Whether the implicit field is set.
   */
  boolean hasImplicit();
  /**
   * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3;</code>
   * @return The implicit.
   */
  org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlow getImplicit();
  /**
   * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3;</code>
   */
  org.a2aproject.sdk.compat03.grpc.ImplicitOAuthFlowOrBuilder getImplicitOrBuilder();

  /**
   * <code>.a2a.v1.PasswordOAuthFlow password = 4;</code>
   * @return Whether the password field is set.
   */
  boolean hasPassword();
  /**
   * <code>.a2a.v1.PasswordOAuthFlow password = 4;</code>
   * @return The password.
   */
  org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlow getPassword();
  /**
   * <code>.a2a.v1.PasswordOAuthFlow password = 4;</code>
   */
  org.a2aproject.sdk.compat03.grpc.PasswordOAuthFlowOrBuilder getPasswordOrBuilder();

  org.a2aproject.sdk.compat03.grpc.OAuthFlows.FlowCase getFlowCase();
}
