// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package org.a2aproject.sdk.compat03.grpc;

@com.google.protobuf.Generated
public interface SecuritySchemeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.SecurityScheme)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.a2a.v1.APIKeySecurityScheme api_key_security_scheme = 1;</code>
   * @return Whether the apiKeySecurityScheme field is set.
   */
  boolean hasApiKeySecurityScheme();
  /**
   * <code>.a2a.v1.APIKeySecurityScheme api_key_security_scheme = 1;</code>
   * @return The apiKeySecurityScheme.
   */
  org.a2aproject.sdk.compat03.grpc.APIKeySecurityScheme getApiKeySecurityScheme();
  /**
   * <code>.a2a.v1.APIKeySecurityScheme api_key_security_scheme = 1;</code>
   */
  org.a2aproject.sdk.compat03.grpc.APIKeySecuritySchemeOrBuilder getApiKeySecuritySchemeOrBuilder();

  /**
   * <code>.a2a.v1.HTTPAuthSecurityScheme http_auth_security_scheme = 2;</code>
   * @return Whether the httpAuthSecurityScheme field is set.
   */
  boolean hasHttpAuthSecurityScheme();
  /**
   * <code>.a2a.v1.HTTPAuthSecurityScheme http_auth_security_scheme = 2;</code>
   * @return The httpAuthSecurityScheme.
   */
  org.a2aproject.sdk.compat03.grpc.HTTPAuthSecurityScheme getHttpAuthSecurityScheme();
  /**
   * <code>.a2a.v1.HTTPAuthSecurityScheme http_auth_security_scheme = 2;</code>
   */
  org.a2aproject.sdk.compat03.grpc.HTTPAuthSecuritySchemeOrBuilder getHttpAuthSecuritySchemeOrBuilder();

  /**
   * <code>.a2a.v1.OAuth2SecurityScheme oauth2_security_scheme = 3;</code>
   * @return Whether the oauth2SecurityScheme field is set.
   */
  boolean hasOauth2SecurityScheme();
  /**
   * <code>.a2a.v1.OAuth2SecurityScheme oauth2_security_scheme = 3;</code>
   * @return The oauth2SecurityScheme.
   */
  org.a2aproject.sdk.compat03.grpc.OAuth2SecurityScheme getOauth2SecurityScheme();
  /**
   * <code>.a2a.v1.OAuth2SecurityScheme oauth2_security_scheme = 3;</code>
   */
  org.a2aproject.sdk.compat03.grpc.OAuth2SecuritySchemeOrBuilder getOauth2SecuritySchemeOrBuilder();

  /**
   * <code>.a2a.v1.OpenIdConnectSecurityScheme open_id_connect_security_scheme = 4;</code>
   * @return Whether the openIdConnectSecurityScheme field is set.
   */
  boolean hasOpenIdConnectSecurityScheme();
  /**
   * <code>.a2a.v1.OpenIdConnectSecurityScheme open_id_connect_security_scheme = 4;</code>
   * @return The openIdConnectSecurityScheme.
   */
  org.a2aproject.sdk.compat03.grpc.OpenIdConnectSecurityScheme getOpenIdConnectSecurityScheme();
  /**
   * <code>.a2a.v1.OpenIdConnectSecurityScheme open_id_connect_security_scheme = 4;</code>
   */
  org.a2aproject.sdk.compat03.grpc.OpenIdConnectSecuritySchemeOrBuilder getOpenIdConnectSecuritySchemeOrBuilder();

  /**
   * <code>.a2a.v1.MutualTlsSecurityScheme mtls_security_scheme = 5;</code>
   * @return Whether the mtlsSecurityScheme field is set.
   */
  boolean hasMtlsSecurityScheme();
  /**
   * <code>.a2a.v1.MutualTlsSecurityScheme mtls_security_scheme = 5;</code>
   * @return The mtlsSecurityScheme.
   */
  org.a2aproject.sdk.compat03.grpc.MutualTlsSecurityScheme getMtlsSecurityScheme();
  /**
   * <code>.a2a.v1.MutualTlsSecurityScheme mtls_security_scheme = 5;</code>
   */
  org.a2aproject.sdk.compat03.grpc.MutualTlsSecuritySchemeOrBuilder getMtlsSecuritySchemeOrBuilder();

  org.a2aproject.sdk.compat03.grpc.SecurityScheme.SchemeCase getSchemeCase();
}
