// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package org.a2aproject.sdk.compat03.grpc;

@com.google.protobuf.Generated
public interface SendMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.SendMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.a2a.v1.Task task = 1;</code>
   * @return Whether the task field is set.
   */
  boolean hasTask();
  /**
   * <code>.a2a.v1.Task task = 1;</code>
   * @return The task.
   */
  org.a2aproject.sdk.compat03.grpc.Task getTask();
  /**
   * <code>.a2a.v1.Task task = 1;</code>
   */
  org.a2aproject.sdk.compat03.grpc.TaskOrBuilder getTaskOrBuilder();

  /**
   * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
   * @return Whether the msg field is set.
   */
  boolean hasMsg();
  /**
   * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
   * @return The msg.
   */
  org.a2aproject.sdk.compat03.grpc.Message getMsg();
  /**
   * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
   */
  org.a2aproject.sdk.compat03.grpc.MessageOrBuilder getMsgOrBuilder();

  org.a2aproject.sdk.compat03.grpc.SendMessageResponse.PayloadCase getPayloadCase();
}
