package org.a2aproject.sdk.compat03.spec;

import java.util.List;
import java.util.Map;

import org.a2aproject.sdk.util.Assert;

/**
 * Represents a file, data structure, or other resource generated by an agent during a task.
 */
public record Artifact_v0_3(String artifactId, String name, String description, List<Part_v0_3<?>> parts, Map<String, Object> metadata,
                            List<String> extensions) {

    public Artifact_v0_3 {
        Assert.checkNotNullParam("artifactId", artifactId);
        Assert.checkNotNullParam("parts", parts);
        if (parts.isEmpty()) {
            throw new IllegalArgumentException("Parts cannot be empty");
        }
    }

    public static class Builder {
        private String artifactId;
        private String name;
        private String description;
        private List<Part_v0_3<?>> parts;
        private Map<String, Object> metadata;
        private List<String> extensions;

        public Builder(){
        }

        public Builder(Artifact_v0_3 existingArtifact) {
            artifactId = existingArtifact.artifactId;
            name = existingArtifact.name;
            description = existingArtifact.description;
            parts = existingArtifact.parts;
            metadata = existingArtifact.metadata;
            extensions = existingArtifact.extensions;
        }

        public Builder artifactId(String artifactId) {
            this.artifactId = artifactId;
            return this;
        }


        public Builder name(String name) {
            this.name = name;
            return this;
        }

        public Builder description(String description) {
            this.description = description;
            return this;
        }

        public Builder parts(List<Part_v0_3<?>> parts) {
            this.parts = parts;
            return this;
        }

        public Builder parts(Part_v0_3<?>... parts) {
            this.parts = List.of(parts);
            return this;
        }

        public Builder metadata(Map<String, Object> metadata) {
            this.metadata = metadata;
            return this;
        }

        public Builder extensions(List<String> extensions) {
            this.extensions = (extensions == null) ? null : List.copyOf(extensions);
            return this;
        }

        public Artifact_v0_3 build() {
            return new Artifact_v0_3(artifactId, name, description, parts, metadata, extensions);
        }
    }
}
