quarkus.http.port=10102
quarkus.grpc.server.port=11002

# File logging
quarkus.log.file.enable=true
quarkus.log.file.path=/tmp/java-current.log
quarkus.log.file.level=DEBUG
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n
