// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public final class A2A extends com.google.protobuf.GeneratedFile {
  private A2A() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "A2A");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_SendMessageConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_SendMessageConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_Task_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_Task_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_TaskStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_TaskStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_Part_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_Part_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_Artifact_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_Artifact_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_TaskStatusUpdateEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_TaskStatusUpdateEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_TaskArtifactUpdateEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_TaskArtifactUpdateEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_AuthenticationInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_AuthenticationInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_AgentInterface_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_AgentInterface_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_AgentCard_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_AgentCard_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_AgentCard_SecuritySchemesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_AgentCard_SecuritySchemesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_AgentProvider_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_AgentProvider_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_AgentCapabilities_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_AgentCapabilities_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_AgentExtension_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_AgentExtension_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_AgentSkill_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_AgentSkill_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_AgentCardSignature_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_AgentCardSignature_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_TaskPushNotificationConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_TaskPushNotificationConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_StringList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_StringList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_SecurityRequirement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_SecurityRequirement_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_SecurityRequirement_SchemesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_SecurityRequirement_SchemesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_SecurityScheme_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_SecurityScheme_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_APIKeySecurityScheme_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_APIKeySecurityScheme_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_HTTPAuthSecurityScheme_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_HTTPAuthSecurityScheme_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_OAuth2SecurityScheme_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_OAuth2SecurityScheme_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_OpenIdConnectSecurityScheme_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_OpenIdConnectSecurityScheme_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_MutualTlsSecurityScheme_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_MutualTlsSecurityScheme_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_OAuthFlows_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_OAuthFlows_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_AuthorizationCodeOAuthFlow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_AuthorizationCodeOAuthFlow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_AuthorizationCodeOAuthFlow_ScopesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_AuthorizationCodeOAuthFlow_ScopesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_ClientCredentialsOAuthFlow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_ClientCredentialsOAuthFlow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_ClientCredentialsOAuthFlow_ScopesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_ClientCredentialsOAuthFlow_ScopesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_ImplicitOAuthFlow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_ImplicitOAuthFlow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_ImplicitOAuthFlow_ScopesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_ImplicitOAuthFlow_ScopesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_PasswordOAuthFlow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_PasswordOAuthFlow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_PasswordOAuthFlow_ScopesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_PasswordOAuthFlow_ScopesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_DeviceCodeOAuthFlow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_DeviceCodeOAuthFlow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_DeviceCodeOAuthFlow_ScopesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_DeviceCodeOAuthFlow_ScopesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_SendMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_SendMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_GetTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_GetTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_ListTasksRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_ListTasksRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_ListTasksResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_ListTasksResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_CancelTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_CancelTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_GetTaskPushNotificationConfigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_GetTaskPushNotificationConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_DeleteTaskPushNotificationConfigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_DeleteTaskPushNotificationConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_SubscribeToTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_SubscribeToTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_ListTaskPushNotificationConfigsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_ListTaskPushNotificationConfigsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_GetExtendedAgentCardRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_GetExtendedAgentCardRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_SendMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_SendMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_StreamResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lf_a2a_v1_ListTaskPushNotificationConfigsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lf_a2a_v1_ListTaskPushNotificationConfigsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ta2a.proto\022\tlf.a2a.v1\032\034google/api/annot" +
      "ations.proto\032\027google/api/client.proto\032\037g" +
      "oogle/api/field_behavior.proto\032\033google/p" +
      "rotobuf/empty.proto\032\034google/protobuf/str" +
      "uct.proto\032\037google/protobuf/timestamp.pro" +
      "to\"\323\001\n\030SendMessageConfiguration\022\035\n\025accep" +
      "ted_output_modes\030\001 \003(\t\022L\n\035task_push_noti" +
      "fication_config\030\002 \001(\0132%.lf.a2a.v1.TaskPu" +
      "shNotificationConfig\022\033\n\016history_length\030\003" +
      " \001(\005H\000\210\001\001\022\032\n\022return_immediately\030\004 \001(\010B\021\n" +
      "\017_history_length\"\317\001\n\004Task\022\017\n\002id\030\001 \001(\tB\003\340" +
      "A\002\022\022\n\ncontext_id\030\002 \001(\t\022*\n\006status\030\003 \001(\0132\025" +
      ".lf.a2a.v1.TaskStatusB\003\340A\002\022&\n\tartifacts\030" +
      "\004 \003(\0132\023.lf.a2a.v1.Artifact\022#\n\007history\030\005 " +
      "\003(\0132\022.lf.a2a.v1.Message\022)\n\010metadata\030\006 \001(" +
      "\0132\027.google.protobuf.Struct\"\212\001\n\nTaskStatu" +
      "s\022(\n\005state\030\001 \001(\0162\024.lf.a2a.v1.TaskStateB\003" +
      "\340A\002\022#\n\007message\030\002 \001(\0132\022.lf.a2a.v1.Message" +
      "\022-\n\ttimestamp\030\003 \001(\0132\032.google.protobuf.Ti" +
      "mestamp\"\270\001\n\004Part\022\016\n\004text\030\001 \001(\tH\000\022\r\n\003raw\030" +
      "\002 \001(\014H\000\022\r\n\003url\030\003 \001(\tH\000\022&\n\004data\030\004 \001(\0132\026.g" +
      "oogle.protobuf.ValueH\000\022)\n\010metadata\030\005 \001(\013" +
      "2\027.google.protobuf.Struct\022\020\n\010filename\030\006 " +
      "\001(\t\022\022\n\nmedia_type\030\007 \001(\tB\t\n\007content\"\353\001\n\007M" +
      "essage\022\027\n\nmessage_id\030\001 \001(\tB\003\340A\002\022\022\n\nconte" +
      "xt_id\030\002 \001(\t\022\017\n\007task_id\030\003 \001(\t\022\"\n\004role\030\004 \001" +
      "(\0162\017.lf.a2a.v1.RoleB\003\340A\002\022#\n\005parts\030\005 \003(\0132" +
      "\017.lf.a2a.v1.PartB\003\340A\002\022)\n\010metadata\030\006 \001(\0132" +
      "\027.google.protobuf.Struct\022\022\n\nextensions\030\007" +
      " \003(\t\022\032\n\022reference_task_ids\030\010 \003(\t\"\253\001\n\010Art" +
      "ifact\022\030\n\013artifact_id\030\001 \001(\tB\003\340A\002\022\014\n\004name\030" +
      "\002 \001(\t\022\023\n\013description\030\003 \001(\t\022#\n\005parts\030\004 \003(" +
      "\0132\017.lf.a2a.v1.PartB\003\340A\002\022)\n\010metadata\030\005 \001(" +
      "\0132\027.google.protobuf.Struct\022\022\n\nextensions" +
      "\030\006 \003(\t\"\235\001\n\025TaskStatusUpdateEvent\022\024\n\007task" +
      "_id\030\001 \001(\tB\003\340A\002\022\027\n\ncontext_id\030\002 \001(\tB\003\340A\002\022" +
      "*\n\006status\030\003 \001(\0132\025.lf.a2a.v1.TaskStatusB\003" +
      "\340A\002\022)\n\010metadata\030\004 \001(\0132\027.google.protobuf." +
      "Struct\"\303\001\n\027TaskArtifactUpdateEvent\022\024\n\007ta" +
      "sk_id\030\001 \001(\tB\003\340A\002\022\027\n\ncontext_id\030\002 \001(\tB\003\340A" +
      "\002\022*\n\010artifact\030\003 \001(\0132\023.lf.a2a.v1.Artifact" +
      "B\003\340A\002\022\016\n\006append\030\004 \001(\010\022\022\n\nlast_chunk\030\005 \001(" +
      "\010\022)\n\010metadata\030\006 \001(\0132\027.google.protobuf.St" +
      "ruct\">\n\022AuthenticationInfo\022\023\n\006scheme\030\001 \001" +
      "(\tB\003\340A\002\022\023\n\013credentials\030\002 \001(\t\"p\n\016AgentInt" +
      "erface\022\020\n\003url\030\001 \001(\tB\003\340A\002\022\035\n\020protocol_bin" +
      "ding\030\002 \001(\tB\003\340A\002\022\016\n\006tenant\030\003 \001(\t\022\035\n\020proto" +
      "col_version\030\004 \001(\tB\003\340A\002\"\306\005\n\tAgentCard\022\021\n\004" +
      "name\030\001 \001(\tB\003\340A\002\022\030\n\013description\030\002 \001(\tB\003\340A" +
      "\002\022<\n\024supported_interfaces\030\003 \003(\0132\031.lf.a2a" +
      ".v1.AgentInterfaceB\003\340A\002\022*\n\010provider\030\004 \001(" +
      "\0132\030.lf.a2a.v1.AgentProvider\022\024\n\007version\030\005" +
      " \001(\tB\003\340A\002\022\036\n\021documentation_url\030\006 \001(\tH\000\210\001" +
      "\001\0227\n\014capabilities\030\007 \001(\0132\034.lf.a2a.v1.Agen" +
      "tCapabilitiesB\003\340A\002\022C\n\020security_schemes\030\010" +
      " \003(\0132).lf.a2a.v1.AgentCard.SecuritySchem" +
      "esEntry\022=\n\025security_requirements\030\t \003(\0132\036" +
      ".lf.a2a.v1.SecurityRequirement\022 \n\023defaul" +
      "t_input_modes\030\n \003(\tB\003\340A\002\022!\n\024default_outp" +
      "ut_modes\030\013 \003(\tB\003\340A\002\022*\n\006skills\030\014 \003(\0132\025.lf" +
      ".a2a.v1.AgentSkillB\003\340A\002\0221\n\nsignatures\030\r " +
      "\003(\0132\035.lf.a2a.v1.AgentCardSignature\022\025\n\010ic" +
      "on_url\030\016 \001(\tH\001\210\001\001\032Q\n\024SecuritySchemesEntr" +
      "y\022\013\n\003key\030\001 \001(\t\022(\n\005value\030\002 \001(\0132\031.lf.a2a.v" +
      "1.SecurityScheme:\0028\001B\024\n\022_documentation_u" +
      "rlB\013\n\t_icon_url\"<\n\rAgentProvider\022\020\n\003url\030" +
      "\001 \001(\tB\003\340A\002\022\031\n\014organization\030\002 \001(\tB\003\340A\002\"\332\001" +
      "\n\021AgentCapabilities\022\026\n\tstreaming\030\001 \001(\010H\000" +
      "\210\001\001\022\037\n\022push_notifications\030\002 \001(\010H\001\210\001\001\022-\n\n" +
      "extensions\030\003 \003(\0132\031.lf.a2a.v1.AgentExtens" +
      "ion\022 \n\023extended_agent_card\030\004 \001(\010H\002\210\001\001B\014\n" +
      "\n_streamingB\025\n\023_push_notificationsB\026\n\024_e" +
      "xtended_agent_card\"m\n\016AgentExtension\022\013\n\003" +
      "uri\030\001 \001(\t\022\023\n\013description\030\002 \001(\t\022\020\n\010requir" +
      "ed\030\003 \001(\010\022\'\n\006params\030\004 \001(\0132\027.google.protob" +
      "uf.Struct\"\331\001\n\nAgentSkill\022\017\n\002id\030\001 \001(\tB\003\340A" +
      "\002\022\021\n\004name\030\002 \001(\tB\003\340A\002\022\030\n\013description\030\003 \001(" +
      "\tB\003\340A\002\022\021\n\004tags\030\004 \003(\tB\003\340A\002\022\020\n\010examples\030\005 " +
      "\003(\t\022\023\n\013input_modes\030\006 \003(\t\022\024\n\014output_modes" +
      "\030\007 \003(\t\022=\n\025security_requirements\030\010 \003(\0132\036." +
      "lf.a2a.v1.SecurityRequirement\"m\n\022AgentCa" +
      "rdSignature\022\026\n\tprotected\030\001 \001(\tB\003\340A\002\022\026\n\ts" +
      "ignature\030\002 \001(\tB\003\340A\002\022\'\n\006header\030\003 \001(\0132\027.go" +
      "ogle.protobuf.Struct\"\241\001\n\032TaskPushNotific" +
      "ationConfig\022\016\n\006tenant\030\001 \001(\t\022\n\n\002id\030\002 \001(\t\022" +
      "\017\n\007task_id\030\003 \001(\t\022\020\n\003url\030\004 \001(\tB\003\340A\002\022\r\n\005to" +
      "ken\030\005 \001(\t\0225\n\016authentication\030\006 \001(\0132\035.lf.a" +
      "2a.v1.AuthenticationInfo\"\032\n\nStringList\022\014" +
      "\n\004list\030\001 \003(\t\"\232\001\n\023SecurityRequirement\022<\n\007" +
      "schemes\030\001 \003(\0132+.lf.a2a.v1.SecurityRequir" +
      "ement.SchemesEntry\032E\n\014SchemesEntry\022\013\n\003ke" +
      "y\030\001 \001(\t\022$\n\005value\030\002 \001(\0132\025.lf.a2a.v1.Strin" +
      "gList:\0028\001\"\200\003\n\016SecurityScheme\022B\n\027api_key_" +
      "security_scheme\030\001 \001(\0132\037.lf.a2a.v1.APIKey" +
      "SecuritySchemeH\000\022F\n\031http_auth_security_s" +
      "cheme\030\002 \001(\0132!.lf.a2a.v1.HTTPAuthSecurity" +
      "SchemeH\000\022A\n\026oauth2_security_scheme\030\003 \001(\013" +
      "2\037.lf.a2a.v1.OAuth2SecuritySchemeH\000\022Q\n\037o" +
      "pen_id_connect_security_scheme\030\004 \001(\0132&.l" +
      "f.a2a.v1.OpenIdConnectSecuritySchemeH\000\022B" +
      "\n\024mtls_security_scheme\030\005 \001(\0132\".lf.a2a.v1" +
      ".MutualTlsSecuritySchemeH\000B\010\n\006scheme\"U\n\024" +
      "APIKeySecurityScheme\022\023\n\013description\030\001 \001(" +
      "\t\022\025\n\010location\030\002 \001(\tB\003\340A\002\022\021\n\004name\030\003 \001(\tB\003" +
      "\340A\002\"Y\n\026HTTPAuthSecurityScheme\022\023\n\013descrip" +
      "tion\030\001 \001(\t\022\023\n\006scheme\030\002 \001(\tB\003\340A\002\022\025\n\rbeare" +
      "r_format\030\003 \001(\t\"s\n\024OAuth2SecurityScheme\022\023" +
      "\n\013description\030\001 \001(\t\022)\n\005flows\030\002 \001(\0132\025.lf." +
      "a2a.v1.OAuthFlowsB\003\340A\002\022\033\n\023oauth2_metadat" +
      "a_url\030\003 \001(\t\"T\n\033OpenIdConnectSecuritySche" +
      "me\022\023\n\013description\030\001 \001(\t\022 \n\023open_id_conne" +
      "ct_url\030\002 \001(\tB\003\340A\002\".\n\027MutualTlsSecuritySc" +
      "heme\022\023\n\013description\030\001 \001(\t\"\301\002\n\nOAuthFlows" +
      "\022C\n\022authorization_code\030\001 \001(\0132%.lf.a2a.v1" +
      ".AuthorizationCodeOAuthFlowH\000\022C\n\022client_" +
      "credentials\030\002 \001(\0132%.lf.a2a.v1.ClientCred" +
      "entialsOAuthFlowH\000\0224\n\010implicit\030\003 \001(\0132\034.l" +
      "f.a2a.v1.ImplicitOAuthFlowB\002\030\001H\000\0224\n\010pass" +
      "word\030\004 \001(\0132\034.lf.a2a.v1.PasswordOAuthFlow" +
      "B\002\030\001H\000\0225\n\013device_code\030\005 \001(\0132\036.lf.a2a.v1." +
      "DeviceCodeOAuthFlowH\000B\006\n\004flow\"\367\001\n\032Author" +
      "izationCodeOAuthFlow\022\036\n\021authorization_ur" +
      "l\030\001 \001(\tB\003\340A\002\022\026\n\ttoken_url\030\002 \001(\tB\003\340A\002\022\023\n\013" +
      "refresh_url\030\003 \001(\t\022F\n\006scopes\030\004 \003(\01321.lf.a" +
      "2a.v1.AuthorizationCodeOAuthFlow.ScopesE" +
      "ntryB\003\340A\002\022\025\n\rpkce_required\030\005 \001(\010\032-\n\013Scop" +
      "esEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"" +
      "\300\001\n\032ClientCredentialsOAuthFlow\022\026\n\ttoken_" +
      "url\030\001 \001(\tB\003\340A\002\022\023\n\013refresh_url\030\002 \001(\t\022F\n\006s" +
      "copes\030\003 \003(\01321.lf.a2a.v1.ClientCredential" +
      "sOAuthFlow.ScopesEntryB\003\340A\002\032-\n\013ScopesEnt" +
      "ry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\254\001\n\021I" +
      "mplicitOAuthFlow\022\031\n\021authorization_url\030\001 " +
      "\001(\t\022\023\n\013refresh_url\030\002 \001(\t\0228\n\006scopes\030\003 \003(\013" +
      "2(.lf.a2a.v1.ImplicitOAuthFlow.ScopesEnt" +
      "ry\032-\n\013ScopesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030" +
      "\002 \001(\t:\0028\001\"\244\001\n\021PasswordOAuthFlow\022\021\n\ttoken" +
      "_url\030\001 \001(\t\022\023\n\013refresh_url\030\002 \001(\t\0228\n\006scope" +
      "s\030\003 \003(\0132(.lf.a2a.v1.PasswordOAuthFlow.Sc" +
      "opesEntry\032-\n\013ScopesEntry\022\013\n\003key\030\001 \001(\t\022\r\n" +
      "\005value\030\002 \001(\t:\0028\001\"\331\001\n\023DeviceCodeOAuthFlow" +
      "\022%\n\030device_authorization_url\030\001 \001(\tB\003\340A\002\022" +
      "\026\n\ttoken_url\030\002 \001(\tB\003\340A\002\022\023\n\013refresh_url\030\003" +
      " \001(\t\022?\n\006scopes\030\004 \003(\0132*.lf.a2a.v1.DeviceC" +
      "odeOAuthFlow.ScopesEntryB\003\340A\002\032-\n\013ScopesE" +
      "ntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\265\001\n" +
      "\022SendMessageRequest\022\016\n\006tenant\030\001 \001(\t\022(\n\007m" +
      "essage\030\002 \001(\0132\022.lf.a2a.v1.MessageB\003\340A\002\022:\n" +
      "\rconfiguration\030\003 \001(\0132#.lf.a2a.v1.SendMes" +
      "sageConfiguration\022)\n\010metadata\030\004 \001(\0132\027.go" +
      "ogle.protobuf.Struct\"a\n\016GetTaskRequest\022\016" +
      "\n\006tenant\030\001 \001(\t\022\017\n\002id\030\002 \001(\tB\003\340A\002\022\033\n\016histo" +
      "ry_length\030\003 \001(\005H\000\210\001\001B\021\n\017_history_length\"" +
      "\270\002\n\020ListTasksRequest\022\016\n\006tenant\030\001 \001(\t\022\022\n\n" +
      "context_id\030\002 \001(\t\022$\n\006status\030\003 \001(\0162\024.lf.a2" +
      "a.v1.TaskState\022\026\n\tpage_size\030\004 \001(\005H\000\210\001\001\022\022" +
      "\n\npage_token\030\005 \001(\t\022\033\n\016history_length\030\006 \001" +
      "(\005H\001\210\001\001\022:\n\026status_timestamp_after\030\007 \001(\0132" +
      "\032.google.protobuf.Timestamp\022\036\n\021include_a" +
      "rtifacts\030\010 \001(\010H\002\210\001\001B\014\n\n_page_sizeB\021\n\017_hi" +
      "story_lengthB\024\n\022_include_artifacts\"\207\001\n\021L" +
      "istTasksResponse\022#\n\005tasks\030\001 \003(\0132\017.lf.a2a" +
      ".v1.TaskB\003\340A\002\022\034\n\017next_page_token\030\002 \001(\tB\003" +
      "\340A\002\022\026\n\tpage_size\030\003 \001(\005B\003\340A\002\022\027\n\ntotal_siz" +
      "e\030\004 \001(\005B\003\340A\002\"_\n\021CancelTaskRequest\022\016\n\006ten" +
      "ant\030\001 \001(\t\022\017\n\002id\030\002 \001(\tB\003\340A\002\022)\n\010metadata\030\003" +
      " \001(\0132\027.google.protobuf.Struct\"]\n$GetTask" +
      "PushNotificationConfigRequest\022\016\n\006tenant\030" +
      "\001 \001(\t\022\024\n\007task_id\030\002 \001(\tB\003\340A\002\022\017\n\002id\030\003 \001(\tB" +
      "\003\340A\002\"`\n\'DeleteTaskPushNotificationConfig" +
      "Request\022\016\n\006tenant\030\001 \001(\t\022\024\n\007task_id\030\002 \001(\t" +
      "B\003\340A\002\022\017\n\002id\030\003 \001(\tB\003\340A\002\"9\n\026SubscribeToTas" +
      "kRequest\022\016\n\006tenant\030\001 \001(\t\022\017\n\002id\030\002 \001(\tB\003\340A" +
      "\002\"u\n&ListTaskPushNotificationConfigsRequ" +
      "est\022\016\n\006tenant\030\004 \001(\t\022\024\n\007task_id\030\001 \001(\tB\003\340A" +
      "\002\022\021\n\tpage_size\030\002 \001(\005\022\022\n\npage_token\030\003 \001(\t" +
      "\"-\n\033GetExtendedAgentCardRequest\022\016\n\006tenan" +
      "t\030\001 \001(\t\"h\n\023SendMessageResponse\022\037\n\004task\030\001" +
      " \001(\0132\017.lf.a2a.v1.TaskH\000\022%\n\007message\030\002 \001(\013" +
      "2\022.lf.a2a.v1.MessageH\000B\t\n\007payload\"\335\001\n\016St" +
      "reamResponse\022\037\n\004task\030\001 \001(\0132\017.lf.a2a.v1.T" +
      "askH\000\022%\n\007message\030\002 \001(\0132\022.lf.a2a.v1.Messa" +
      "geH\000\0229\n\rstatus_update\030\003 \001(\0132 .lf.a2a.v1." +
      "TaskStatusUpdateEventH\000\022=\n\017artifact_upda" +
      "te\030\004 \001(\0132\".lf.a2a.v1.TaskArtifactUpdateE" +
      "ventH\000B\t\n\007payload\"z\n\'ListTaskPushNotific" +
      "ationConfigsResponse\0226\n\007configs\030\001 \003(\0132%." +
      "lf.a2a.v1.TaskPushNotificationConfig\022\027\n\017" +
      "next_page_token\030\002 \001(\t*\371\001\n\tTaskState\022\032\n\026T" +
      "ASK_STATE_UNSPECIFIED\020\000\022\030\n\024TASK_STATE_SU" +
      "BMITTED\020\001\022\026\n\022TASK_STATE_WORKING\020\002\022\030\n\024TAS" +
      "K_STATE_COMPLETED\020\003\022\025\n\021TASK_STATE_FAILED" +
      "\020\004\022\027\n\023TASK_STATE_CANCELED\020\005\022\035\n\031TASK_STAT" +
      "E_INPUT_REQUIRED\020\006\022\027\n\023TASK_STATE_REJECTE" +
      "D\020\007\022\034\n\030TASK_STATE_AUTH_REQUIRED\020\010*;\n\004Rol" +
      "e\022\024\n\020ROLE_UNSPECIFIED\020\000\022\r\n\tROLE_USER\020\001\022\016" +
      "\n\nROLE_AGENT\020\0022\227\017\n\nA2AService\022\203\001\n\013SendMe" +
      "ssage\022\035.lf.a2a.v1.SendMessageRequest\032\036.l" +
      "f.a2a.v1.SendMessageResponse\"5\202\323\344\223\002/\"\r/m" +
      "essage:send:\001*Z\033\"\026/{tenant}/message:send" +
      ":\001*\022\215\001\n\024SendStreamingMessage\022\035.lf.a2a.v1" +
      ".SendMessageRequest\032\031.lf.a2a.v1.StreamRe" +
      "sponse\"9\202\323\344\223\0023\"\017/message:stream:\001*Z\035\"\030/{" +
      "tenant}/message:stream:\001*0\001\022k\n\007GetTask\022\031" +
      ".lf.a2a.v1.GetTaskRequest\032\017.lf.a2a.v1.Ta" +
      "sk\"4\332A\002id\202\323\344\223\002)\022\r/tasks/{id=*}Z\030\022\026/{tena" +
      "nt}/tasks/{id=*}\022i\n\tListTasks\022\033.lf.a2a.v" +
      "1.ListTasksRequest\032\034.lf.a2a.v1.ListTasks" +
      "Response\"!\202\323\344\223\002\033\022\006/tasksZ\021\022\017/{tenant}/ta" +
      "sks\022\200\001\n\nCancelTask\022\034.lf.a2a.v1.CancelTas" +
      "kRequest\032\017.lf.a2a.v1.Task\"C\202\323\344\223\002=\"\024/task" +
      "s/{id=*}:cancel:\001*Z\"\"\035/{tenant}/tasks/{i" +
      "d=*}:cancel:\001*\022\226\001\n\017SubscribeToTask\022!.lf." +
      "a2a.v1.SubscribeToTaskRequest\032\031.lf.a2a.v" +
      "1.StreamResponse\"C\202\323\344\223\002=\022\027/tasks/{id=*}:" +
      "subscribeZ\"\022 /{tenant}/tasks/{id=*}:subs" +
      "cribe0\001\022\363\001\n CreateTaskPushNotificationCo" +
      "nfig\022%.lf.a2a.v1.TaskPushNotificationCon" +
      "fig\032%.lf.a2a.v1.TaskPushNotificationConf" +
      "ig\"\200\001\332A\016task_id,config\202\323\344\223\002i\"*/tasks/{ta" +
      "sk_id=*}/pushNotificationConfigs:\001*Z8\"3/" +
      "{tenant}/tasks/{task_id=*}/pushNotificat" +
      "ionConfigs:\001*\022\376\001\n\035GetTaskPushNotificatio" +
      "nConfig\022/.lf.a2a.v1.GetTaskPushNotificat" +
      "ionConfigRequest\032%.lf.a2a.v1.TaskPushNot" +
      "ificationConfig\"\204\001\332A\ntask_id,id\202\323\344\223\002q\0221/" +
      "tasks/{task_id=*}/pushNotificationConfig" +
      "s/{id=*}Z<\022:/{tenant}/tasks/{task_id=*}/" +
      "pushNotificationConfigs/{id=*}\022\375\001\n\037ListT" +
      "askPushNotificationConfigs\0221.lf.a2a.v1.L" +
      "istTaskPushNotificationConfigsRequest\0322." +
      "lf.a2a.v1.ListTaskPushNotificationConfig" +
      "sResponse\"s\332A\007task_id\202\323\344\223\002c\022*/tasks/{tas" +
      "k_id=*}/pushNotificationConfigsZ5\0223/{ten" +
      "ant}/tasks/{task_id=*}/pushNotificationC" +
      "onfigs\022\217\001\n\024GetExtendedAgentCard\022&.lf.a2a" +
      ".v1.GetExtendedAgentCardRequest\032\024.lf.a2a" +
      ".v1.AgentCard\"9\202\323\344\223\0023\022\022/extendedAgentCar" +
      "dZ\035\022\033/{tenant}/extendedAgentCard\022\365\001\n Del" +
      "eteTaskPushNotificationConfig\0222.lf.a2a.v" +
      "1.DeleteTaskPushNotificationConfigReques" +
      "t\032\026.google.protobuf.Empty\"\204\001\332A\ntask_id,i" +
      "d\202\323\344\223\002q*1/tasks/{task_id=*}/pushNotifica" +
      "tionConfigs/{id=*}Z<*:/{tenant}/tasks/{t" +
      "ask_id=*}/pushNotificationConfigs/{id=*}" +
      "B=\n\013io.a2a.grpcB\003A2AP\001Z\033google.golang.or" +
      "g/lf/a2a/v1\252\002\tLf.A2a.V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.ClientProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_lf_a2a_v1_SendMessageConfiguration_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_lf_a2a_v1_SendMessageConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_SendMessageConfiguration_descriptor,
        new java.lang.String[] { "AcceptedOutputModes", "TaskPushNotificationConfig", "HistoryLength", "ReturnImmediately", });
    internal_static_lf_a2a_v1_Task_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_lf_a2a_v1_Task_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_Task_descriptor,
        new java.lang.String[] { "Id", "ContextId", "Status", "Artifacts", "History", "Metadata", });
    internal_static_lf_a2a_v1_TaskStatus_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_lf_a2a_v1_TaskStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_TaskStatus_descriptor,
        new java.lang.String[] { "State", "Message", "Timestamp", });
    internal_static_lf_a2a_v1_Part_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_lf_a2a_v1_Part_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_Part_descriptor,
        new java.lang.String[] { "Text", "Raw", "Url", "Data", "Metadata", "Filename", "MediaType", "Content", });
    internal_static_lf_a2a_v1_Message_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_lf_a2a_v1_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_Message_descriptor,
        new java.lang.String[] { "MessageId", "ContextId", "TaskId", "Role", "Parts", "Metadata", "Extensions", "ReferenceTaskIds", });
    internal_static_lf_a2a_v1_Artifact_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_lf_a2a_v1_Artifact_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_Artifact_descriptor,
        new java.lang.String[] { "ArtifactId", "Name", "Description", "Parts", "Metadata", "Extensions", });
    internal_static_lf_a2a_v1_TaskStatusUpdateEvent_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_lf_a2a_v1_TaskStatusUpdateEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_TaskStatusUpdateEvent_descriptor,
        new java.lang.String[] { "TaskId", "ContextId", "Status", "Metadata", });
    internal_static_lf_a2a_v1_TaskArtifactUpdateEvent_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_lf_a2a_v1_TaskArtifactUpdateEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_TaskArtifactUpdateEvent_descriptor,
        new java.lang.String[] { "TaskId", "ContextId", "Artifact", "Append", "LastChunk", "Metadata", });
    internal_static_lf_a2a_v1_AuthenticationInfo_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_lf_a2a_v1_AuthenticationInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_AuthenticationInfo_descriptor,
        new java.lang.String[] { "Scheme", "Credentials", });
    internal_static_lf_a2a_v1_AgentInterface_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_lf_a2a_v1_AgentInterface_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_AgentInterface_descriptor,
        new java.lang.String[] { "Url", "ProtocolBinding", "Tenant", "ProtocolVersion", });
    internal_static_lf_a2a_v1_AgentCard_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_lf_a2a_v1_AgentCard_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_AgentCard_descriptor,
        new java.lang.String[] { "Name", "Description", "SupportedInterfaces", "Provider", "Version", "DocumentationUrl", "Capabilities", "SecuritySchemes", "SecurityRequirements", "DefaultInputModes", "DefaultOutputModes", "Skills", "Signatures", "IconUrl", });
    internal_static_lf_a2a_v1_AgentCard_SecuritySchemesEntry_descriptor =
      internal_static_lf_a2a_v1_AgentCard_descriptor.getNestedType(0);
    internal_static_lf_a2a_v1_AgentCard_SecuritySchemesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_AgentCard_SecuritySchemesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_lf_a2a_v1_AgentProvider_descriptor =
      getDescriptor().getMessageType(11);
    internal_static_lf_a2a_v1_AgentProvider_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_AgentProvider_descriptor,
        new java.lang.String[] { "Url", "Organization", });
    internal_static_lf_a2a_v1_AgentCapabilities_descriptor =
      getDescriptor().getMessageType(12);
    internal_static_lf_a2a_v1_AgentCapabilities_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_AgentCapabilities_descriptor,
        new java.lang.String[] { "Streaming", "PushNotifications", "Extensions", "ExtendedAgentCard", });
    internal_static_lf_a2a_v1_AgentExtension_descriptor =
      getDescriptor().getMessageType(13);
    internal_static_lf_a2a_v1_AgentExtension_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_AgentExtension_descriptor,
        new java.lang.String[] { "Uri", "Description", "Required", "Params", });
    internal_static_lf_a2a_v1_AgentSkill_descriptor =
      getDescriptor().getMessageType(14);
    internal_static_lf_a2a_v1_AgentSkill_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_AgentSkill_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Tags", "Examples", "InputModes", "OutputModes", "SecurityRequirements", });
    internal_static_lf_a2a_v1_AgentCardSignature_descriptor =
      getDescriptor().getMessageType(15);
    internal_static_lf_a2a_v1_AgentCardSignature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_AgentCardSignature_descriptor,
        new java.lang.String[] { "Protected", "Signature", "Header", });
    internal_static_lf_a2a_v1_TaskPushNotificationConfig_descriptor =
      getDescriptor().getMessageType(16);
    internal_static_lf_a2a_v1_TaskPushNotificationConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_TaskPushNotificationConfig_descriptor,
        new java.lang.String[] { "Tenant", "Id", "TaskId", "Url", "Token", "Authentication", });
    internal_static_lf_a2a_v1_StringList_descriptor =
      getDescriptor().getMessageType(17);
    internal_static_lf_a2a_v1_StringList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_StringList_descriptor,
        new java.lang.String[] { "List", });
    internal_static_lf_a2a_v1_SecurityRequirement_descriptor =
      getDescriptor().getMessageType(18);
    internal_static_lf_a2a_v1_SecurityRequirement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_SecurityRequirement_descriptor,
        new java.lang.String[] { "Schemes", });
    internal_static_lf_a2a_v1_SecurityRequirement_SchemesEntry_descriptor =
      internal_static_lf_a2a_v1_SecurityRequirement_descriptor.getNestedType(0);
    internal_static_lf_a2a_v1_SecurityRequirement_SchemesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_SecurityRequirement_SchemesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_lf_a2a_v1_SecurityScheme_descriptor =
      getDescriptor().getMessageType(19);
    internal_static_lf_a2a_v1_SecurityScheme_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_SecurityScheme_descriptor,
        new java.lang.String[] { "ApiKeySecurityScheme", "HttpAuthSecurityScheme", "Oauth2SecurityScheme", "OpenIdConnectSecurityScheme", "MtlsSecurityScheme", "Scheme", });
    internal_static_lf_a2a_v1_APIKeySecurityScheme_descriptor =
      getDescriptor().getMessageType(20);
    internal_static_lf_a2a_v1_APIKeySecurityScheme_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_APIKeySecurityScheme_descriptor,
        new java.lang.String[] { "Description", "Location", "Name", });
    internal_static_lf_a2a_v1_HTTPAuthSecurityScheme_descriptor =
      getDescriptor().getMessageType(21);
    internal_static_lf_a2a_v1_HTTPAuthSecurityScheme_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_HTTPAuthSecurityScheme_descriptor,
        new java.lang.String[] { "Description", "Scheme", "BearerFormat", });
    internal_static_lf_a2a_v1_OAuth2SecurityScheme_descriptor =
      getDescriptor().getMessageType(22);
    internal_static_lf_a2a_v1_OAuth2SecurityScheme_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_OAuth2SecurityScheme_descriptor,
        new java.lang.String[] { "Description", "Flows", "Oauth2MetadataUrl", });
    internal_static_lf_a2a_v1_OpenIdConnectSecurityScheme_descriptor =
      getDescriptor().getMessageType(23);
    internal_static_lf_a2a_v1_OpenIdConnectSecurityScheme_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_OpenIdConnectSecurityScheme_descriptor,
        new java.lang.String[] { "Description", "OpenIdConnectUrl", });
    internal_static_lf_a2a_v1_MutualTlsSecurityScheme_descriptor =
      getDescriptor().getMessageType(24);
    internal_static_lf_a2a_v1_MutualTlsSecurityScheme_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_MutualTlsSecurityScheme_descriptor,
        new java.lang.String[] { "Description", });
    internal_static_lf_a2a_v1_OAuthFlows_descriptor =
      getDescriptor().getMessageType(25);
    internal_static_lf_a2a_v1_OAuthFlows_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_OAuthFlows_descriptor,
        new java.lang.String[] { "AuthorizationCode", "ClientCredentials", "Implicit", "Password", "DeviceCode", "Flow", });
    internal_static_lf_a2a_v1_AuthorizationCodeOAuthFlow_descriptor =
      getDescriptor().getMessageType(26);
    internal_static_lf_a2a_v1_AuthorizationCodeOAuthFlow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_AuthorizationCodeOAuthFlow_descriptor,
        new java.lang.String[] { "AuthorizationUrl", "TokenUrl", "RefreshUrl", "Scopes", "PkceRequired", });
    internal_static_lf_a2a_v1_AuthorizationCodeOAuthFlow_ScopesEntry_descriptor =
      internal_static_lf_a2a_v1_AuthorizationCodeOAuthFlow_descriptor.getNestedType(0);
    internal_static_lf_a2a_v1_AuthorizationCodeOAuthFlow_ScopesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_AuthorizationCodeOAuthFlow_ScopesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_lf_a2a_v1_ClientCredentialsOAuthFlow_descriptor =
      getDescriptor().getMessageType(27);
    internal_static_lf_a2a_v1_ClientCredentialsOAuthFlow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_ClientCredentialsOAuthFlow_descriptor,
        new java.lang.String[] { "TokenUrl", "RefreshUrl", "Scopes", });
    internal_static_lf_a2a_v1_ClientCredentialsOAuthFlow_ScopesEntry_descriptor =
      internal_static_lf_a2a_v1_ClientCredentialsOAuthFlow_descriptor.getNestedType(0);
    internal_static_lf_a2a_v1_ClientCredentialsOAuthFlow_ScopesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_ClientCredentialsOAuthFlow_ScopesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_lf_a2a_v1_ImplicitOAuthFlow_descriptor =
      getDescriptor().getMessageType(28);
    internal_static_lf_a2a_v1_ImplicitOAuthFlow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_ImplicitOAuthFlow_descriptor,
        new java.lang.String[] { "AuthorizationUrl", "RefreshUrl", "Scopes", });
    internal_static_lf_a2a_v1_ImplicitOAuthFlow_ScopesEntry_descriptor =
      internal_static_lf_a2a_v1_ImplicitOAuthFlow_descriptor.getNestedType(0);
    internal_static_lf_a2a_v1_ImplicitOAuthFlow_ScopesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_ImplicitOAuthFlow_ScopesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_lf_a2a_v1_PasswordOAuthFlow_descriptor =
      getDescriptor().getMessageType(29);
    internal_static_lf_a2a_v1_PasswordOAuthFlow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_PasswordOAuthFlow_descriptor,
        new java.lang.String[] { "TokenUrl", "RefreshUrl", "Scopes", });
    internal_static_lf_a2a_v1_PasswordOAuthFlow_ScopesEntry_descriptor =
      internal_static_lf_a2a_v1_PasswordOAuthFlow_descriptor.getNestedType(0);
    internal_static_lf_a2a_v1_PasswordOAuthFlow_ScopesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_PasswordOAuthFlow_ScopesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_lf_a2a_v1_DeviceCodeOAuthFlow_descriptor =
      getDescriptor().getMessageType(30);
    internal_static_lf_a2a_v1_DeviceCodeOAuthFlow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_DeviceCodeOAuthFlow_descriptor,
        new java.lang.String[] { "DeviceAuthorizationUrl", "TokenUrl", "RefreshUrl", "Scopes", });
    internal_static_lf_a2a_v1_DeviceCodeOAuthFlow_ScopesEntry_descriptor =
      internal_static_lf_a2a_v1_DeviceCodeOAuthFlow_descriptor.getNestedType(0);
    internal_static_lf_a2a_v1_DeviceCodeOAuthFlow_ScopesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_DeviceCodeOAuthFlow_ScopesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_lf_a2a_v1_SendMessageRequest_descriptor =
      getDescriptor().getMessageType(31);
    internal_static_lf_a2a_v1_SendMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_SendMessageRequest_descriptor,
        new java.lang.String[] { "Tenant", "Message", "Configuration", "Metadata", });
    internal_static_lf_a2a_v1_GetTaskRequest_descriptor =
      getDescriptor().getMessageType(32);
    internal_static_lf_a2a_v1_GetTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_GetTaskRequest_descriptor,
        new java.lang.String[] { "Tenant", "Id", "HistoryLength", });
    internal_static_lf_a2a_v1_ListTasksRequest_descriptor =
      getDescriptor().getMessageType(33);
    internal_static_lf_a2a_v1_ListTasksRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_ListTasksRequest_descriptor,
        new java.lang.String[] { "Tenant", "ContextId", "Status", "PageSize", "PageToken", "HistoryLength", "StatusTimestampAfter", "IncludeArtifacts", });
    internal_static_lf_a2a_v1_ListTasksResponse_descriptor =
      getDescriptor().getMessageType(34);
    internal_static_lf_a2a_v1_ListTasksResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_ListTasksResponse_descriptor,
        new java.lang.String[] { "Tasks", "NextPageToken", "PageSize", "TotalSize", });
    internal_static_lf_a2a_v1_CancelTaskRequest_descriptor =
      getDescriptor().getMessageType(35);
    internal_static_lf_a2a_v1_CancelTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_CancelTaskRequest_descriptor,
        new java.lang.String[] { "Tenant", "Id", "Metadata", });
    internal_static_lf_a2a_v1_GetTaskPushNotificationConfigRequest_descriptor =
      getDescriptor().getMessageType(36);
    internal_static_lf_a2a_v1_GetTaskPushNotificationConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_GetTaskPushNotificationConfigRequest_descriptor,
        new java.lang.String[] { "Tenant", "TaskId", "Id", });
    internal_static_lf_a2a_v1_DeleteTaskPushNotificationConfigRequest_descriptor =
      getDescriptor().getMessageType(37);
    internal_static_lf_a2a_v1_DeleteTaskPushNotificationConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_DeleteTaskPushNotificationConfigRequest_descriptor,
        new java.lang.String[] { "Tenant", "TaskId", "Id", });
    internal_static_lf_a2a_v1_SubscribeToTaskRequest_descriptor =
      getDescriptor().getMessageType(38);
    internal_static_lf_a2a_v1_SubscribeToTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_SubscribeToTaskRequest_descriptor,
        new java.lang.String[] { "Tenant", "Id", });
    internal_static_lf_a2a_v1_ListTaskPushNotificationConfigsRequest_descriptor =
      getDescriptor().getMessageType(39);
    internal_static_lf_a2a_v1_ListTaskPushNotificationConfigsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_ListTaskPushNotificationConfigsRequest_descriptor,
        new java.lang.String[] { "Tenant", "TaskId", "PageSize", "PageToken", });
    internal_static_lf_a2a_v1_GetExtendedAgentCardRequest_descriptor =
      getDescriptor().getMessageType(40);
    internal_static_lf_a2a_v1_GetExtendedAgentCardRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_GetExtendedAgentCardRequest_descriptor,
        new java.lang.String[] { "Tenant", });
    internal_static_lf_a2a_v1_SendMessageResponse_descriptor =
      getDescriptor().getMessageType(41);
    internal_static_lf_a2a_v1_SendMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_SendMessageResponse_descriptor,
        new java.lang.String[] { "Task", "Message", "Payload", });
    internal_static_lf_a2a_v1_StreamResponse_descriptor =
      getDescriptor().getMessageType(42);
    internal_static_lf_a2a_v1_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_StreamResponse_descriptor,
        new java.lang.String[] { "Task", "Message", "StatusUpdate", "ArtifactUpdate", "Payload", });
    internal_static_lf_a2a_v1_ListTaskPushNotificationConfigsResponse_descriptor =
      getDescriptor().getMessageType(43);
    internal_static_lf_a2a_v1_ListTaskPushNotificationConfigsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lf_a2a_v1_ListTaskPushNotificationConfigsResponse_descriptor,
        new java.lang.String[] { "Configs", "NextPageToken", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
