// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface AgentExtensionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.AgentExtension)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The unique URI identifying the extension.
   * </pre>
   *
   * <code>string uri = 1;</code>
   * @return The uri.
   */
  java.lang.String getUri();
  /**
   * <pre>
   * The unique URI identifying the extension.
   * </pre>
   *
   * <code>string uri = 1;</code>
   * @return The bytes for uri.
   */
  com.google.protobuf.ByteString
      getUriBytes();

  /**
   * <pre>
   * A human-readable description of how this agent uses the extension.
   * </pre>
   *
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * A human-readable description of how this agent uses the extension.
   * </pre>
   *
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * If true, the client must understand and comply with the extension's requirements.
   * </pre>
   *
   * <code>bool required = 3;</code>
   * @return The required.
   */
  boolean getRequired();

  /**
   * <pre>
   * Optional, extension-specific configuration parameters.
   * </pre>
   *
   * <code>.google.protobuf.Struct params = 4;</code>
   * @return Whether the params field is set.
   */
  boolean hasParams();
  /**
   * <pre>
   * Optional, extension-specific configuration parameters.
   * </pre>
   *
   * <code>.google.protobuf.Struct params = 4;</code>
   * @return The params.
   */
  com.google.protobuf.Struct getParams();
  /**
   * <pre>
   * Optional, extension-specific configuration parameters.
   * </pre>
   *
   * <code>.google.protobuf.Struct params = 4;</code>
   */
  com.google.protobuf.StructOrBuilder getParamsOrBuilder();
}
