// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface AgentProviderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.AgentProvider)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A URL for the agent provider's website or relevant documentation.
   * Example: "https://ai.google.dev"
   * </pre>
   *
   * <code>string url = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <pre>
   * A URL for the agent provider's website or relevant documentation.
   * Example: "https://ai.google.dev"
   * </pre>
   *
   * <code>string url = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <pre>
   * The name of the agent provider's organization.
   * Example: "Google"
   * </pre>
   *
   * <code>string organization = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The organization.
   */
  java.lang.String getOrganization();
  /**
   * <pre>
   * The name of the agent provider's organization.
   * Example: "Google"
   * </pre>
   *
   * <code>string organization = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for organization.
   */
  com.google.protobuf.ByteString
      getOrganizationBytes();
}
