// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface AgentCardSignatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.AgentCardSignature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The protected JWS header for the signature. This is always a
   * base64url-encoded JSON object. Required.
   * </pre>
   *
   * <code>string protected = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The protected.
   */
  java.lang.String getProtected();
  /**
   * <pre>
   * The protected JWS header for the signature. This is always a
   * base64url-encoded JSON object. Required.
   * </pre>
   *
   * <code>string protected = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for protected.
   */
  com.google.protobuf.ByteString
      getProtectedBytes();

  /**
   * <pre>
   * The computed signature, base64url-encoded. Required.
   * </pre>
   *
   * <code>string signature = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The signature.
   */
  java.lang.String getSignature();
  /**
   * <pre>
   * The computed signature, base64url-encoded. Required.
   * </pre>
   *
   * <code>string signature = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for signature.
   */
  com.google.protobuf.ByteString
      getSignatureBytes();

  /**
   * <pre>
   * The unprotected JWS header values.
   * </pre>
   *
   * <code>.google.protobuf.Struct header = 3;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <pre>
   * The unprotected JWS header values.
   * </pre>
   *
   * <code>.google.protobuf.Struct header = 3;</code>
   * @return The header.
   */
  com.google.protobuf.Struct getHeader();
  /**
   * <pre>
   * The unprotected JWS header values.
   * </pre>
   *
   * <code>.google.protobuf.Struct header = 3;</code>
   */
  com.google.protobuf.StructOrBuilder getHeaderOrBuilder();
}
