// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface APIKeySecuritySchemeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.APIKeySecurityScheme)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * An optional description for the security scheme.
   * </pre>
   *
   * <code>string description = 1;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * An optional description for the security scheme.
   * </pre>
   *
   * <code>string description = 1;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * The location of the API key. Valid values are "query", "header", or "cookie".
   * </pre>
   *
   * <code>string location = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   * <pre>
   * The location of the API key. Valid values are "query", "header", or "cookie".
   * </pre>
   *
   * <code>string location = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <pre>
   * The name of the header, query, or cookie parameter to be used.
   * </pre>
   *
   * <code>string name = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The name of the header, query, or cookie parameter to be used.
   * </pre>
   *
   * <code>string name = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
