// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface DataPartOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.DataPart)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The structured data content.
   * </pre>
   *
   * <code>.google.protobuf.Struct data = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <pre>
   * The structured data content.
   * </pre>
   *
   * <code>.google.protobuf.Struct data = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The data.
   */
  com.google.protobuf.Struct getData();
  /**
   * <pre>
   * The structured data content.
   * </pre>
   *
   * <code>.google.protobuf.Struct data = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.protobuf.StructOrBuilder getDataOrBuilder();
}
