// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface FilePartOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.FilePart)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A URL pointing to the file's content.
   * </pre>
   *
   * <code>string file_with_uri = 1;</code>
   * @return Whether the fileWithUri field is set.
   */
  boolean hasFileWithUri();
  /**
   * <pre>
   * A URL pointing to the file's content.
   * </pre>
   *
   * <code>string file_with_uri = 1;</code>
   * @return The fileWithUri.
   */
  java.lang.String getFileWithUri();
  /**
   * <pre>
   * A URL pointing to the file's content.
   * </pre>
   *
   * <code>string file_with_uri = 1;</code>
   * @return The bytes for fileWithUri.
   */
  com.google.protobuf.ByteString
      getFileWithUriBytes();

  /**
   * <pre>
   * The base64-encoded content of the file.
   * </pre>
   *
   * <code>bytes file_with_bytes = 2;</code>
   * @return Whether the fileWithBytes field is set.
   */
  boolean hasFileWithBytes();
  /**
   * <pre>
   * The base64-encoded content of the file.
   * </pre>
   *
   * <code>bytes file_with_bytes = 2;</code>
   * @return The fileWithBytes.
   */
  com.google.protobuf.ByteString getFileWithBytes();

  /**
   * <pre>
   * The media type of the file (e.g., "application/pdf").
   * </pre>
   *
   * <code>string media_type = 3;</code>
   * @return The mediaType.
   */
  java.lang.String getMediaType();
  /**
   * <pre>
   * The media type of the file (e.g., "application/pdf").
   * </pre>
   *
   * <code>string media_type = 3;</code>
   * @return The bytes for mediaType.
   */
  com.google.protobuf.ByteString
      getMediaTypeBytes();

  /**
   * <pre>
   * An optional name for the file (e.g., "document.pdf").
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * An optional name for the file (e.g., "document.pdf").
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  io.a2a.grpc.FilePart.FileCase getFileCase();
}
