// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface HTTPAuthSecuritySchemeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.HTTPAuthSecurityScheme)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * An optional description for the security scheme.
   * </pre>
   *
   * <code>string description = 1;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * An optional description for the security scheme.
   * </pre>
   *
   * <code>string description = 1;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * The name of the HTTP Authentication scheme to be used in the Authorization header,
   * as defined in RFC7235 (e.g., "Bearer").
   * This value should be registered in the IANA Authentication Scheme registry.
   * </pre>
   *
   * <code>string scheme = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The scheme.
   */
  java.lang.String getScheme();
  /**
   * <pre>
   * The name of the HTTP Authentication scheme to be used in the Authorization header,
   * as defined in RFC7235 (e.g., "Bearer").
   * This value should be registered in the IANA Authentication Scheme registry.
   * </pre>
   *
   * <code>string scheme = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for scheme.
   */
  com.google.protobuf.ByteString
      getSchemeBytes();

  /**
   * <pre>
   * A hint to the client to identify how the bearer token is formatted (e.g., "JWT").
   * This is primarily for documentation purposes.
   * </pre>
   *
   * <code>string bearer_format = 3;</code>
   * @return The bearerFormat.
   */
  java.lang.String getBearerFormat();
  /**
   * <pre>
   * A hint to the client to identify how the bearer token is formatted (e.g., "JWT").
   * This is primarily for documentation purposes.
   * </pre>
   *
   * <code>string bearer_format = 3;</code>
   * @return The bytes for bearerFormat.
   */
  com.google.protobuf.ByteString
      getBearerFormatBytes();
}
