// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface ListTasksRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.ListTasksRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Filter tasks by context ID to get tasks from a specific conversation or session.
   * </pre>
   *
   * <code>string context_id = 1;</code>
   * @return The contextId.
   */
  java.lang.String getContextId();
  /**
   * <pre>
   * Filter tasks by context ID to get tasks from a specific conversation or session.
   * </pre>
   *
   * <code>string context_id = 1;</code>
   * @return The bytes for contextId.
   */
  com.google.protobuf.ByteString
      getContextIdBytes();

  /**
   * <pre>
   * Filter tasks by their current status state.
   * </pre>
   *
   * <code>.a2a.v1.TaskState status = 2;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <pre>
   * Filter tasks by their current status state.
   * </pre>
   *
   * <code>.a2a.v1.TaskState status = 2;</code>
   * @return The status.
   */
  io.a2a.grpc.TaskState getStatus();

  /**
   * <pre>
   * Maximum number of tasks to return. Must be between 1 and 100.
   * Defaults to 50 if not specified.
   * </pre>
   *
   * <code>optional int32 page_size = 3;</code>
   * @return Whether the pageSize field is set.
   */
  boolean hasPageSize();
  /**
   * <pre>
   * Maximum number of tasks to return. Must be between 1 and 100.
   * Defaults to 50 if not specified.
   * </pre>
   *
   * <code>optional int32 page_size = 3;</code>
   * @return The pageSize.
   */
  int getPageSize();

  /**
   * <pre>
   * Token for pagination. Use the next_page_token from a previous ListTasksResponse.
   * </pre>
   *
   * <code>string page_token = 4;</code>
   * @return The pageToken.
   */
  java.lang.String getPageToken();
  /**
   * <pre>
   * Token for pagination. Use the next_page_token from a previous ListTasksResponse.
   * </pre>
   *
   * <code>string page_token = 4;</code>
   * @return The bytes for pageToken.
   */
  com.google.protobuf.ByteString
      getPageTokenBytes();

  /**
   * <pre>
   * The maximum number of messages to include in each task's history.
   * </pre>
   *
   * <code>optional int32 history_length = 5;</code>
   * @return Whether the historyLength field is set.
   */
  boolean hasHistoryLength();
  /**
   * <pre>
   * The maximum number of messages to include in each task's history.
   * </pre>
   *
   * <code>optional int32 history_length = 5;</code>
   * @return The historyLength.
   */
  int getHistoryLength();

  /**
   * <pre>
   * Filter tasks updated after this timestamp (milliseconds since epoch).
   * Only tasks with a last updated time greater than or equal to this value will be returned.
   * </pre>
   *
   * <code>int64 last_updated_after = 6;</code>
   * @return The lastUpdatedAfter.
   */
  long getLastUpdatedAfter();

  /**
   * <pre>
   * Whether to include artifacts in the returned tasks.
   * Defaults to false to reduce payload size.
   * </pre>
   *
   * <code>optional bool include_artifacts = 7;</code>
   * @return Whether the includeArtifacts field is set.
   */
  boolean hasIncludeArtifacts();
  /**
   * <pre>
   * Whether to include artifacts in the returned tasks.
   * Defaults to false to reduce payload size.
   * </pre>
   *
   * <code>optional bool include_artifacts = 7;</code>
   * @return The includeArtifacts.
   */
  boolean getIncludeArtifacts();

  /**
   * <pre>
   * Request-specific metadata.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 8;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * Request-specific metadata.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 8;</code>
   * @return The metadata.
   */
  com.google.protobuf.Struct getMetadata();
  /**
   * <pre>
   * Request-specific metadata.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 8;</code>
   */
  com.google.protobuf.StructOrBuilder getMetadataOrBuilder();
}
