// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

/**
 * <pre>
 * --8&lt;-- [start:ListTasksRequest]
 * </pre>
 *
 * Protobuf type {@code a2a.v1.ListTasksRequest}
 */
@com.google.protobuf.Generated
public final class ListTasksRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:a2a.v1.ListTasksRequest)
    ListTasksRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      ListTasksRequest.class.getName());
  }
  // Use ListTasksRequest.newBuilder() to construct.
  private ListTasksRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListTasksRequest() {
    contextId_ = "";
    status_ = 0;
    pageToken_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.a2a.grpc.A2A.internal_static_a2a_v1_ListTasksRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.a2a.grpc.A2A.internal_static_a2a_v1_ListTasksRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.a2a.grpc.ListTasksRequest.class, io.a2a.grpc.ListTasksRequest.Builder.class);
  }

  private int bitField0_;
  public static final int CONTEXT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object contextId_ = "";
  /**
   * <pre>
   * Filter tasks by context ID to get tasks from a specific conversation
   * or session.
   * </pre>
   *
   * <code>string context_id = 1;</code>
   * @return The contextId.
   */
  @java.lang.Override
  public java.lang.String getContextId() {
    java.lang.Object ref = contextId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contextId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Filter tasks by context ID to get tasks from a specific conversation
   * or session.
   * </pre>
   *
   * <code>string context_id = 1;</code>
   * @return The bytes for contextId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContextIdBytes() {
    java.lang.Object ref = contextId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contextId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private int status_ = 0;
  /**
   * <pre>
   * Filter tasks by their current status state.
   * </pre>
   *
   * <code>.a2a.v1.TaskState status = 2;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <pre>
   * Filter tasks by their current status state.
   * </pre>
   *
   * <code>.a2a.v1.TaskState status = 2;</code>
   * @return The status.
   */
  @java.lang.Override public io.a2a.grpc.TaskState getStatus() {
    io.a2a.grpc.TaskState result = io.a2a.grpc.TaskState.forNumber(status_);
    return result == null ? io.a2a.grpc.TaskState.UNRECOGNIZED : result;
  }

  public static final int PAGE_SIZE_FIELD_NUMBER = 3;
  private int pageSize_ = 0;
  /**
   * <pre>
   * Maximum number of tasks to return. Must be between 1 and 100.
   * Defaults to 50 if not specified.
   * </pre>
   *
   * <code>int32 page_size = 3;</code>
   * @return The pageSize.
   */
  @java.lang.Override
  public int getPageSize() {
    return pageSize_;
  }

  public static final int PAGE_TOKEN_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pageToken_ = "";
  /**
   * <pre>
   * Token for pagination. Use the next_page_token from a previous
   * ListTasksResponse.
   * </pre>
   *
   * <code>string page_token = 4;</code>
   * @return The pageToken.
   */
  @java.lang.Override
  public java.lang.String getPageToken() {
    java.lang.Object ref = pageToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pageToken_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Token for pagination. Use the next_page_token from a previous
   * ListTasksResponse.
   * </pre>
   *
   * <code>string page_token = 4;</code>
   * @return The bytes for pageToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPageTokenBytes() {
    java.lang.Object ref = pageToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pageToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HISTORY_LENGTH_FIELD_NUMBER = 5;
  private int historyLength_ = 0;
  /**
   * <pre>
   * Number of recent messages to include in each task's history.
   * Must be non-negative. Defaults to 0 if not specified.
   * </pre>
   *
   * <code>int32 history_length = 5;</code>
   * @return The historyLength.
   */
  @java.lang.Override
  public int getHistoryLength() {
    return historyLength_;
  }

  public static final int LAST_UPDATED_TIME_FIELD_NUMBER = 6;
  private com.google.protobuf.Timestamp lastUpdatedTime_;
  /**
   * <pre>
   * Filter tasks updated after this timestamp. Only tasks with a last
   * updated time greater than or equal to this value will be returned.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp last_updated_time = 6;</code>
   * @return Whether the lastUpdatedTime field is set.
   */
  @java.lang.Override
  public boolean hasLastUpdatedTime() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Filter tasks updated after this timestamp. Only tasks with a last
   * updated time greater than or equal to this value will be returned.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp last_updated_time = 6;</code>
   * @return The lastUpdatedTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getLastUpdatedTime() {
    return lastUpdatedTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdatedTime_;
  }
  /**
   * <pre>
   * Filter tasks updated after this timestamp. Only tasks with a last
   * updated time greater than or equal to this value will be returned.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp last_updated_time = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getLastUpdatedTimeOrBuilder() {
    return lastUpdatedTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdatedTime_;
  }

  public static final int INCLUDE_ARTIFACTS_FIELD_NUMBER = 7;
  private boolean includeArtifacts_ = false;
  /**
   * <pre>
   * Whether to include artifacts in the returned tasks.
   * Defaults to false to reduce payload size.
   * </pre>
   *
   * <code>bool include_artifacts = 7;</code>
   * @return The includeArtifacts.
   */
  @java.lang.Override
  public boolean getIncludeArtifacts() {
    return includeArtifacts_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contextId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, contextId_);
    }
    if (status_ != io.a2a.grpc.TaskState.TASK_STATE_UNSPECIFIED.getNumber()) {
      output.writeEnum(2, status_);
    }
    if (pageSize_ != 0) {
      output.writeInt32(3, pageSize_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pageToken_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, pageToken_);
    }
    if (historyLength_ != 0) {
      output.writeInt32(5, historyLength_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(6, getLastUpdatedTime());
    }
    if (includeArtifacts_ != false) {
      output.writeBool(7, includeArtifacts_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contextId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, contextId_);
    }
    if (status_ != io.a2a.grpc.TaskState.TASK_STATE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, status_);
    }
    if (pageSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, pageSize_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pageToken_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, pageToken_);
    }
    if (historyLength_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, historyLength_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getLastUpdatedTime());
    }
    if (includeArtifacts_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, includeArtifacts_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.a2a.grpc.ListTasksRequest)) {
      return super.equals(obj);
    }
    io.a2a.grpc.ListTasksRequest other = (io.a2a.grpc.ListTasksRequest) obj;

    if (!getContextId()
        .equals(other.getContextId())) return false;
    if (status_ != other.status_) return false;
    if (getPageSize()
        != other.getPageSize()) return false;
    if (!getPageToken()
        .equals(other.getPageToken())) return false;
    if (getHistoryLength()
        != other.getHistoryLength()) return false;
    if (hasLastUpdatedTime() != other.hasLastUpdatedTime()) return false;
    if (hasLastUpdatedTime()) {
      if (!getLastUpdatedTime()
          .equals(other.getLastUpdatedTime())) return false;
    }
    if (getIncludeArtifacts()
        != other.getIncludeArtifacts()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTEXT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getContextId().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + PAGE_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getPageSize();
    hash = (37 * hash) + PAGE_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getPageToken().hashCode();
    hash = (37 * hash) + HISTORY_LENGTH_FIELD_NUMBER;
    hash = (53 * hash) + getHistoryLength();
    if (hasLastUpdatedTime()) {
      hash = (37 * hash) + LAST_UPDATED_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getLastUpdatedTime().hashCode();
    }
    hash = (37 * hash) + INCLUDE_ARTIFACTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIncludeArtifacts());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.a2a.grpc.ListTasksRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.ListTasksRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.ListTasksRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.ListTasksRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.ListTasksRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.ListTasksRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.ListTasksRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.a2a.grpc.ListTasksRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.a2a.grpc.ListTasksRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.a2a.grpc.ListTasksRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.a2a.grpc.ListTasksRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.a2a.grpc.ListTasksRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.a2a.grpc.ListTasksRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * --8&lt;-- [start:ListTasksRequest]
   * </pre>
   *
   * Protobuf type {@code a2a.v1.ListTasksRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:a2a.v1.ListTasksRequest)
      io.a2a.grpc.ListTasksRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_ListTasksRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_ListTasksRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.a2a.grpc.ListTasksRequest.class, io.a2a.grpc.ListTasksRequest.Builder.class);
    }

    // Construct using io.a2a.grpc.ListTasksRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetLastUpdatedTimeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      contextId_ = "";
      status_ = 0;
      pageSize_ = 0;
      pageToken_ = "";
      historyLength_ = 0;
      lastUpdatedTime_ = null;
      if (lastUpdatedTimeBuilder_ != null) {
        lastUpdatedTimeBuilder_.dispose();
        lastUpdatedTimeBuilder_ = null;
      }
      includeArtifacts_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_ListTasksRequest_descriptor;
    }

    @java.lang.Override
    public io.a2a.grpc.ListTasksRequest getDefaultInstanceForType() {
      return io.a2a.grpc.ListTasksRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.a2a.grpc.ListTasksRequest build() {
      io.a2a.grpc.ListTasksRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.a2a.grpc.ListTasksRequest buildPartial() {
      io.a2a.grpc.ListTasksRequest result = new io.a2a.grpc.ListTasksRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.a2a.grpc.ListTasksRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.contextId_ = contextId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.pageSize_ = pageSize_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.pageToken_ = pageToken_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.historyLength_ = historyLength_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.lastUpdatedTime_ = lastUpdatedTimeBuilder_ == null
            ? lastUpdatedTime_
            : lastUpdatedTimeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.includeArtifacts_ = includeArtifacts_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.a2a.grpc.ListTasksRequest) {
        return mergeFrom((io.a2a.grpc.ListTasksRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.a2a.grpc.ListTasksRequest other) {
      if (other == io.a2a.grpc.ListTasksRequest.getDefaultInstance()) return this;
      if (!other.getContextId().isEmpty()) {
        contextId_ = other.contextId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.getPageSize() != 0) {
        setPageSize(other.getPageSize());
      }
      if (!other.getPageToken().isEmpty()) {
        pageToken_ = other.pageToken_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getHistoryLength() != 0) {
        setHistoryLength(other.getHistoryLength());
      }
      if (other.hasLastUpdatedTime()) {
        mergeLastUpdatedTime(other.getLastUpdatedTime());
      }
      if (other.getIncludeArtifacts() != false) {
        setIncludeArtifacts(other.getIncludeArtifacts());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              contextId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              pageSize_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              pageToken_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              historyLength_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              input.readMessage(
                  internalGetLastUpdatedTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              includeArtifacts_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object contextId_ = "";
    /**
     * <pre>
     * Filter tasks by context ID to get tasks from a specific conversation
     * or session.
     * </pre>
     *
     * <code>string context_id = 1;</code>
     * @return The contextId.
     */
    public java.lang.String getContextId() {
      java.lang.Object ref = contextId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contextId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Filter tasks by context ID to get tasks from a specific conversation
     * or session.
     * </pre>
     *
     * <code>string context_id = 1;</code>
     * @return The bytes for contextId.
     */
    public com.google.protobuf.ByteString
        getContextIdBytes() {
      java.lang.Object ref = contextId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contextId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Filter tasks by context ID to get tasks from a specific conversation
     * or session.
     * </pre>
     *
     * <code>string context_id = 1;</code>
     * @param value The contextId to set.
     * @return This builder for chaining.
     */
    public Builder setContextId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      contextId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Filter tasks by context ID to get tasks from a specific conversation
     * or session.
     * </pre>
     *
     * <code>string context_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearContextId() {
      contextId_ = getDefaultInstance().getContextId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Filter tasks by context ID to get tasks from a specific conversation
     * or session.
     * </pre>
     *
     * <code>string context_id = 1;</code>
     * @param value The bytes for contextId to set.
     * @return This builder for chaining.
     */
    public Builder setContextIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      contextId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <pre>
     * Filter tasks by their current status state.
     * </pre>
     *
     * <code>.a2a.v1.TaskState status = 2;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <pre>
     * Filter tasks by their current status state.
     * </pre>
     *
     * <code>.a2a.v1.TaskState status = 2;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Filter tasks by their current status state.
     * </pre>
     *
     * <code>.a2a.v1.TaskState status = 2;</code>
     * @return The status.
     */
    @java.lang.Override
    public io.a2a.grpc.TaskState getStatus() {
      io.a2a.grpc.TaskState result = io.a2a.grpc.TaskState.forNumber(status_);
      return result == null ? io.a2a.grpc.TaskState.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Filter tasks by their current status state.
     * </pre>
     *
     * <code>.a2a.v1.TaskState status = 2;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(io.a2a.grpc.TaskState value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000002;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Filter tasks by their current status state.
     * </pre>
     *
     * <code>.a2a.v1.TaskState status = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000002);
      status_ = 0;
      onChanged();
      return this;
    }

    private int pageSize_ ;
    /**
     * <pre>
     * Maximum number of tasks to return. Must be between 1 and 100.
     * Defaults to 50 if not specified.
     * </pre>
     *
     * <code>int32 page_size = 3;</code>
     * @return The pageSize.
     */
    @java.lang.Override
    public int getPageSize() {
      return pageSize_;
    }
    /**
     * <pre>
     * Maximum number of tasks to return. Must be between 1 and 100.
     * Defaults to 50 if not specified.
     * </pre>
     *
     * <code>int32 page_size = 3;</code>
     * @param value The pageSize to set.
     * @return This builder for chaining.
     */
    public Builder setPageSize(int value) {

      pageSize_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Maximum number of tasks to return. Must be between 1 and 100.
     * Defaults to 50 if not specified.
     * </pre>
     *
     * <code>int32 page_size = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageSize() {
      bitField0_ = (bitField0_ & ~0x00000004);
      pageSize_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object pageToken_ = "";
    /**
     * <pre>
     * Token for pagination. Use the next_page_token from a previous
     * ListTasksResponse.
     * </pre>
     *
     * <code>string page_token = 4;</code>
     * @return The pageToken.
     */
    public java.lang.String getPageToken() {
      java.lang.Object ref = pageToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pageToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Token for pagination. Use the next_page_token from a previous
     * ListTasksResponse.
     * </pre>
     *
     * <code>string page_token = 4;</code>
     * @return The bytes for pageToken.
     */
    public com.google.protobuf.ByteString
        getPageTokenBytes() {
      java.lang.Object ref = pageToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pageToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Token for pagination. Use the next_page_token from a previous
     * ListTasksResponse.
     * </pre>
     *
     * <code>string page_token = 4;</code>
     * @param value The pageToken to set.
     * @return This builder for chaining.
     */
    public Builder setPageToken(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pageToken_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Token for pagination. Use the next_page_token from a previous
     * ListTasksResponse.
     * </pre>
     *
     * <code>string page_token = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageToken() {
      pageToken_ = getDefaultInstance().getPageToken();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Token for pagination. Use the next_page_token from a previous
     * ListTasksResponse.
     * </pre>
     *
     * <code>string page_token = 4;</code>
     * @param value The bytes for pageToken to set.
     * @return This builder for chaining.
     */
    public Builder setPageTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pageToken_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int historyLength_ ;
    /**
     * <pre>
     * Number of recent messages to include in each task's history.
     * Must be non-negative. Defaults to 0 if not specified.
     * </pre>
     *
     * <code>int32 history_length = 5;</code>
     * @return The historyLength.
     */
    @java.lang.Override
    public int getHistoryLength() {
      return historyLength_;
    }
    /**
     * <pre>
     * Number of recent messages to include in each task's history.
     * Must be non-negative. Defaults to 0 if not specified.
     * </pre>
     *
     * <code>int32 history_length = 5;</code>
     * @param value The historyLength to set.
     * @return This builder for chaining.
     */
    public Builder setHistoryLength(int value) {

      historyLength_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Number of recent messages to include in each task's history.
     * Must be non-negative. Defaults to 0 if not specified.
     * </pre>
     *
     * <code>int32 history_length = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearHistoryLength() {
      bitField0_ = (bitField0_ & ~0x00000010);
      historyLength_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp lastUpdatedTime_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastUpdatedTimeBuilder_;
    /**
     * <pre>
     * Filter tasks updated after this timestamp. Only tasks with a last
     * updated time greater than or equal to this value will be returned.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_updated_time = 6;</code>
     * @return Whether the lastUpdatedTime field is set.
     */
    public boolean hasLastUpdatedTime() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * Filter tasks updated after this timestamp. Only tasks with a last
     * updated time greater than or equal to this value will be returned.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_updated_time = 6;</code>
     * @return The lastUpdatedTime.
     */
    public com.google.protobuf.Timestamp getLastUpdatedTime() {
      if (lastUpdatedTimeBuilder_ == null) {
        return lastUpdatedTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdatedTime_;
      } else {
        return lastUpdatedTimeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Filter tasks updated after this timestamp. Only tasks with a last
     * updated time greater than or equal to this value will be returned.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_updated_time = 6;</code>
     */
    public Builder setLastUpdatedTime(com.google.protobuf.Timestamp value) {
      if (lastUpdatedTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastUpdatedTime_ = value;
      } else {
        lastUpdatedTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Filter tasks updated after this timestamp. Only tasks with a last
     * updated time greater than or equal to this value will be returned.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_updated_time = 6;</code>
     */
    public Builder setLastUpdatedTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (lastUpdatedTimeBuilder_ == null) {
        lastUpdatedTime_ = builderForValue.build();
      } else {
        lastUpdatedTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Filter tasks updated after this timestamp. Only tasks with a last
     * updated time greater than or equal to this value will be returned.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_updated_time = 6;</code>
     */
    public Builder mergeLastUpdatedTime(com.google.protobuf.Timestamp value) {
      if (lastUpdatedTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          lastUpdatedTime_ != null &&
          lastUpdatedTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getLastUpdatedTimeBuilder().mergeFrom(value);
        } else {
          lastUpdatedTime_ = value;
        }
      } else {
        lastUpdatedTimeBuilder_.mergeFrom(value);
      }
      if (lastUpdatedTime_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Filter tasks updated after this timestamp. Only tasks with a last
     * updated time greater than or equal to this value will be returned.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_updated_time = 6;</code>
     */
    public Builder clearLastUpdatedTime() {
      bitField0_ = (bitField0_ & ~0x00000020);
      lastUpdatedTime_ = null;
      if (lastUpdatedTimeBuilder_ != null) {
        lastUpdatedTimeBuilder_.dispose();
        lastUpdatedTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Filter tasks updated after this timestamp. Only tasks with a last
     * updated time greater than or equal to this value will be returned.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_updated_time = 6;</code>
     */
    public com.google.protobuf.Timestamp.Builder getLastUpdatedTimeBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return internalGetLastUpdatedTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Filter tasks updated after this timestamp. Only tasks with a last
     * updated time greater than or equal to this value will be returned.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_updated_time = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getLastUpdatedTimeOrBuilder() {
      if (lastUpdatedTimeBuilder_ != null) {
        return lastUpdatedTimeBuilder_.getMessageOrBuilder();
      } else {
        return lastUpdatedTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdatedTime_;
      }
    }
    /**
     * <pre>
     * Filter tasks updated after this timestamp. Only tasks with a last
     * updated time greater than or equal to this value will be returned.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_updated_time = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetLastUpdatedTimeFieldBuilder() {
      if (lastUpdatedTimeBuilder_ == null) {
        lastUpdatedTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getLastUpdatedTime(),
                getParentForChildren(),
                isClean());
        lastUpdatedTime_ = null;
      }
      return lastUpdatedTimeBuilder_;
    }

    private boolean includeArtifacts_ ;
    /**
     * <pre>
     * Whether to include artifacts in the returned tasks.
     * Defaults to false to reduce payload size.
     * </pre>
     *
     * <code>bool include_artifacts = 7;</code>
     * @return The includeArtifacts.
     */
    @java.lang.Override
    public boolean getIncludeArtifacts() {
      return includeArtifacts_;
    }
    /**
     * <pre>
     * Whether to include artifacts in the returned tasks.
     * Defaults to false to reduce payload size.
     * </pre>
     *
     * <code>bool include_artifacts = 7;</code>
     * @param value The includeArtifacts to set.
     * @return This builder for chaining.
     */
    public Builder setIncludeArtifacts(boolean value) {

      includeArtifacts_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether to include artifacts in the returned tasks.
     * Defaults to false to reduce payload size.
     * </pre>
     *
     * <code>bool include_artifacts = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearIncludeArtifacts() {
      bitField0_ = (bitField0_ & ~0x00000040);
      includeArtifacts_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:a2a.v1.ListTasksRequest)
  }

  // @@protoc_insertion_point(class_scope:a2a.v1.ListTasksRequest)
  private static final io.a2a.grpc.ListTasksRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.a2a.grpc.ListTasksRequest();
  }

  public static io.a2a.grpc.ListTasksRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListTasksRequest>
      PARSER = new com.google.protobuf.AbstractParser<ListTasksRequest>() {
    @java.lang.Override
    public ListTasksRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListTasksRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListTasksRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.a2a.grpc.ListTasksRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

