// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface ListTasksResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.ListTasksResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Array of tasks matching the specified criteria.
   * </pre>
   *
   * <code>repeated .a2a.v1.Task tasks = 1;</code>
   */
  java.util.List<io.a2a.grpc.Task> 
      getTasksList();
  /**
   * <pre>
   * Array of tasks matching the specified criteria.
   * </pre>
   *
   * <code>repeated .a2a.v1.Task tasks = 1;</code>
   */
  io.a2a.grpc.Task getTasks(int index);
  /**
   * <pre>
   * Array of tasks matching the specified criteria.
   * </pre>
   *
   * <code>repeated .a2a.v1.Task tasks = 1;</code>
   */
  int getTasksCount();
  /**
   * <pre>
   * Array of tasks matching the specified criteria.
   * </pre>
   *
   * <code>repeated .a2a.v1.Task tasks = 1;</code>
   */
  java.util.List<? extends io.a2a.grpc.TaskOrBuilder> 
      getTasksOrBuilderList();
  /**
   * <pre>
   * Array of tasks matching the specified criteria.
   * </pre>
   *
   * <code>repeated .a2a.v1.Task tasks = 1;</code>
   */
  io.a2a.grpc.TaskOrBuilder getTasksOrBuilder(
      int index);

  /**
   * <pre>
   * Token for retrieving the next page of results.
   * Empty string if no more results.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The nextPageToken.
   */
  java.lang.String getNextPageToken();
  /**
   * <pre>
   * Token for retrieving the next page of results.
   * Empty string if no more results.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The bytes for nextPageToken.
   */
  com.google.protobuf.ByteString
      getNextPageTokenBytes();

  /**
   * <pre>
   * Total number of tasks available (before pagination).
   * </pre>
   *
   * <code>int32 total_size = 3;</code>
   * @return The totalSize.
   */
  int getTotalSize();
}
