// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

/**
 * <pre>
 * --8&lt;-- [start:ListTasksResponse]
 * Result object for tasks/list method containing an array of tasks and pagination information.
 * </pre>
 *
 * Protobuf type {@code a2a.v1.ListTasksResponse}
 */
@com.google.protobuf.Generated
public final class ListTasksResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:a2a.v1.ListTasksResponse)
    ListTasksResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      ListTasksResponse.class.getName());
  }
  // Use ListTasksResponse.newBuilder() to construct.
  private ListTasksResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListTasksResponse() {
    tasks_ = java.util.Collections.emptyList();
    nextPageToken_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.a2a.grpc.A2A.internal_static_a2a_v1_ListTasksResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.a2a.grpc.A2A.internal_static_a2a_v1_ListTasksResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.a2a.grpc.ListTasksResponse.class, io.a2a.grpc.ListTasksResponse.Builder.class);
  }

  public static final int TASKS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<io.a2a.grpc.Task> tasks_;
  /**
   * <pre>
   * Array of tasks matching the specified criteria.
   * </pre>
   *
   * <code>repeated .a2a.v1.Task tasks = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  @java.lang.Override
  public java.util.List<io.a2a.grpc.Task> getTasksList() {
    return tasks_;
  }
  /**
   * <pre>
   * Array of tasks matching the specified criteria.
   * </pre>
   *
   * <code>repeated .a2a.v1.Task tasks = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.a2a.grpc.TaskOrBuilder> 
      getTasksOrBuilderList() {
    return tasks_;
  }
  /**
   * <pre>
   * Array of tasks matching the specified criteria.
   * </pre>
   *
   * <code>repeated .a2a.v1.Task tasks = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  @java.lang.Override
  public int getTasksCount() {
    return tasks_.size();
  }
  /**
   * <pre>
   * Array of tasks matching the specified criteria.
   * </pre>
   *
   * <code>repeated .a2a.v1.Task tasks = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  @java.lang.Override
  public io.a2a.grpc.Task getTasks(int index) {
    return tasks_.get(index);
  }
  /**
   * <pre>
   * Array of tasks matching the specified criteria.
   * </pre>
   *
   * <code>repeated .a2a.v1.Task tasks = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  @java.lang.Override
  public io.a2a.grpc.TaskOrBuilder getTasksOrBuilder(
      int index) {
    return tasks_.get(index);
  }

  public static final int NEXT_PAGE_TOKEN_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nextPageToken_ = "";
  /**
   * <pre>
   * Token for retrieving the next page. Empty string if no more results.
   * </pre>
   *
   * <code>string next_page_token = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The nextPageToken.
   */
  @java.lang.Override
  public java.lang.String getNextPageToken() {
    java.lang.Object ref = nextPageToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nextPageToken_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Token for retrieving the next page. Empty string if no more results.
   * </pre>
   *
   * <code>string next_page_token = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for nextPageToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNextPageTokenBytes() {
    java.lang.Object ref = nextPageToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nextPageToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGE_SIZE_FIELD_NUMBER = 3;
  private int pageSize_ = 0;
  /**
   * <pre>
   * The size of page requested.
   * </pre>
   *
   * <code>int32 page_size = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The pageSize.
   */
  @java.lang.Override
  public int getPageSize() {
    return pageSize_;
  }

  public static final int TOTAL_SIZE_FIELD_NUMBER = 4;
  private int totalSize_ = 0;
  /**
   * <pre>
   * Total number of tasks available (before pagination).
   * </pre>
   *
   * <code>int32 total_size = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The totalSize.
   */
  @java.lang.Override
  public int getTotalSize() {
    return totalSize_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < tasks_.size(); i++) {
      output.writeMessage(1, tasks_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nextPageToken_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, nextPageToken_);
    }
    if (pageSize_ != 0) {
      output.writeInt32(3, pageSize_);
    }
    if (totalSize_ != 0) {
      output.writeInt32(4, totalSize_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < tasks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, tasks_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nextPageToken_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, nextPageToken_);
    }
    if (pageSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, pageSize_);
    }
    if (totalSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, totalSize_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.a2a.grpc.ListTasksResponse)) {
      return super.equals(obj);
    }
    io.a2a.grpc.ListTasksResponse other = (io.a2a.grpc.ListTasksResponse) obj;

    if (!getTasksList()
        .equals(other.getTasksList())) return false;
    if (!getNextPageToken()
        .equals(other.getNextPageToken())) return false;
    if (getPageSize()
        != other.getPageSize()) return false;
    if (getTotalSize()
        != other.getTotalSize()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTasksCount() > 0) {
      hash = (37 * hash) + TASKS_FIELD_NUMBER;
      hash = (53 * hash) + getTasksList().hashCode();
    }
    hash = (37 * hash) + NEXT_PAGE_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getNextPageToken().hashCode();
    hash = (37 * hash) + PAGE_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getPageSize();
    hash = (37 * hash) + TOTAL_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getTotalSize();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.a2a.grpc.ListTasksResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.ListTasksResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.ListTasksResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.ListTasksResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.ListTasksResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.ListTasksResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.ListTasksResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.a2a.grpc.ListTasksResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.a2a.grpc.ListTasksResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.a2a.grpc.ListTasksResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.a2a.grpc.ListTasksResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.a2a.grpc.ListTasksResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.a2a.grpc.ListTasksResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * --8&lt;-- [start:ListTasksResponse]
   * Result object for tasks/list method containing an array of tasks and pagination information.
   * </pre>
   *
   * Protobuf type {@code a2a.v1.ListTasksResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:a2a.v1.ListTasksResponse)
      io.a2a.grpc.ListTasksResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_ListTasksResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_ListTasksResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.a2a.grpc.ListTasksResponse.class, io.a2a.grpc.ListTasksResponse.Builder.class);
    }

    // Construct using io.a2a.grpc.ListTasksResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (tasksBuilder_ == null) {
        tasks_ = java.util.Collections.emptyList();
      } else {
        tasks_ = null;
        tasksBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      nextPageToken_ = "";
      pageSize_ = 0;
      totalSize_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_ListTasksResponse_descriptor;
    }

    @java.lang.Override
    public io.a2a.grpc.ListTasksResponse getDefaultInstanceForType() {
      return io.a2a.grpc.ListTasksResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.a2a.grpc.ListTasksResponse build() {
      io.a2a.grpc.ListTasksResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.a2a.grpc.ListTasksResponse buildPartial() {
      io.a2a.grpc.ListTasksResponse result = new io.a2a.grpc.ListTasksResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.a2a.grpc.ListTasksResponse result) {
      if (tasksBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          tasks_ = java.util.Collections.unmodifiableList(tasks_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.tasks_ = tasks_;
      } else {
        result.tasks_ = tasksBuilder_.build();
      }
    }

    private void buildPartial0(io.a2a.grpc.ListTasksResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.nextPageToken_ = nextPageToken_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.pageSize_ = pageSize_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.totalSize_ = totalSize_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.a2a.grpc.ListTasksResponse) {
        return mergeFrom((io.a2a.grpc.ListTasksResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.a2a.grpc.ListTasksResponse other) {
      if (other == io.a2a.grpc.ListTasksResponse.getDefaultInstance()) return this;
      if (tasksBuilder_ == null) {
        if (!other.tasks_.isEmpty()) {
          if (tasks_.isEmpty()) {
            tasks_ = other.tasks_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTasksIsMutable();
            tasks_.addAll(other.tasks_);
          }
          onChanged();
        }
      } else {
        if (!other.tasks_.isEmpty()) {
          if (tasksBuilder_.isEmpty()) {
            tasksBuilder_.dispose();
            tasksBuilder_ = null;
            tasks_ = other.tasks_;
            bitField0_ = (bitField0_ & ~0x00000001);
            tasksBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetTasksFieldBuilder() : null;
          } else {
            tasksBuilder_.addAllMessages(other.tasks_);
          }
        }
      }
      if (!other.getNextPageToken().isEmpty()) {
        nextPageToken_ = other.nextPageToken_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getPageSize() != 0) {
        setPageSize(other.getPageSize());
      }
      if (other.getTotalSize() != 0) {
        setTotalSize(other.getTotalSize());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.a2a.grpc.Task m =
                  input.readMessage(
                      io.a2a.grpc.Task.parser(),
                      extensionRegistry);
              if (tasksBuilder_ == null) {
                ensureTasksIsMutable();
                tasks_.add(m);
              } else {
                tasksBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              nextPageToken_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              pageSize_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              totalSize_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<io.a2a.grpc.Task> tasks_ =
      java.util.Collections.emptyList();
    private void ensureTasksIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        tasks_ = new java.util.ArrayList<io.a2a.grpc.Task>(tasks_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.a2a.grpc.Task, io.a2a.grpc.Task.Builder, io.a2a.grpc.TaskOrBuilder> tasksBuilder_;

    /**
     * <pre>
     * Array of tasks matching the specified criteria.
     * </pre>
     *
     * <code>repeated .a2a.v1.Task tasks = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public java.util.List<io.a2a.grpc.Task> getTasksList() {
      if (tasksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tasks_);
      } else {
        return tasksBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Array of tasks matching the specified criteria.
     * </pre>
     *
     * <code>repeated .a2a.v1.Task tasks = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public int getTasksCount() {
      if (tasksBuilder_ == null) {
        return tasks_.size();
      } else {
        return tasksBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Array of tasks matching the specified criteria.
     * </pre>
     *
     * <code>repeated .a2a.v1.Task tasks = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public io.a2a.grpc.Task getTasks(int index) {
      if (tasksBuilder_ == null) {
        return tasks_.get(index);
      } else {
        return tasksBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Array of tasks matching the specified criteria.
     * </pre>
     *
     * <code>repeated .a2a.v1.Task tasks = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setTasks(
        int index, io.a2a.grpc.Task value) {
      if (tasksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTasksIsMutable();
        tasks_.set(index, value);
        onChanged();
      } else {
        tasksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Array of tasks matching the specified criteria.
     * </pre>
     *
     * <code>repeated .a2a.v1.Task tasks = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setTasks(
        int index, io.a2a.grpc.Task.Builder builderForValue) {
      if (tasksBuilder_ == null) {
        ensureTasksIsMutable();
        tasks_.set(index, builderForValue.build());
        onChanged();
      } else {
        tasksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Array of tasks matching the specified criteria.
     * </pre>
     *
     * <code>repeated .a2a.v1.Task tasks = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder addTasks(io.a2a.grpc.Task value) {
      if (tasksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTasksIsMutable();
        tasks_.add(value);
        onChanged();
      } else {
        tasksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Array of tasks matching the specified criteria.
     * </pre>
     *
     * <code>repeated .a2a.v1.Task tasks = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder addTasks(
        int index, io.a2a.grpc.Task value) {
      if (tasksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTasksIsMutable();
        tasks_.add(index, value);
        onChanged();
      } else {
        tasksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Array of tasks matching the specified criteria.
     * </pre>
     *
     * <code>repeated .a2a.v1.Task tasks = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder addTasks(
        io.a2a.grpc.Task.Builder builderForValue) {
      if (tasksBuilder_ == null) {
        ensureTasksIsMutable();
        tasks_.add(builderForValue.build());
        onChanged();
      } else {
        tasksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Array of tasks matching the specified criteria.
     * </pre>
     *
     * <code>repeated .a2a.v1.Task tasks = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder addTasks(
        int index, io.a2a.grpc.Task.Builder builderForValue) {
      if (tasksBuilder_ == null) {
        ensureTasksIsMutable();
        tasks_.add(index, builderForValue.build());
        onChanged();
      } else {
        tasksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Array of tasks matching the specified criteria.
     * </pre>
     *
     * <code>repeated .a2a.v1.Task tasks = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder addAllTasks(
        java.lang.Iterable<? extends io.a2a.grpc.Task> values) {
      if (tasksBuilder_ == null) {
        ensureTasksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tasks_);
        onChanged();
      } else {
        tasksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Array of tasks matching the specified criteria.
     * </pre>
     *
     * <code>repeated .a2a.v1.Task tasks = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder clearTasks() {
      if (tasksBuilder_ == null) {
        tasks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        tasksBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Array of tasks matching the specified criteria.
     * </pre>
     *
     * <code>repeated .a2a.v1.Task tasks = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder removeTasks(int index) {
      if (tasksBuilder_ == null) {
        ensureTasksIsMutable();
        tasks_.remove(index);
        onChanged();
      } else {
        tasksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Array of tasks matching the specified criteria.
     * </pre>
     *
     * <code>repeated .a2a.v1.Task tasks = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public io.a2a.grpc.Task.Builder getTasksBuilder(
        int index) {
      return internalGetTasksFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Array of tasks matching the specified criteria.
     * </pre>
     *
     * <code>repeated .a2a.v1.Task tasks = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public io.a2a.grpc.TaskOrBuilder getTasksOrBuilder(
        int index) {
      if (tasksBuilder_ == null) {
        return tasks_.get(index);  } else {
        return tasksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Array of tasks matching the specified criteria.
     * </pre>
     *
     * <code>repeated .a2a.v1.Task tasks = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public java.util.List<? extends io.a2a.grpc.TaskOrBuilder> 
         getTasksOrBuilderList() {
      if (tasksBuilder_ != null) {
        return tasksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tasks_);
      }
    }
    /**
     * <pre>
     * Array of tasks matching the specified criteria.
     * </pre>
     *
     * <code>repeated .a2a.v1.Task tasks = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public io.a2a.grpc.Task.Builder addTasksBuilder() {
      return internalGetTasksFieldBuilder().addBuilder(
          io.a2a.grpc.Task.getDefaultInstance());
    }
    /**
     * <pre>
     * Array of tasks matching the specified criteria.
     * </pre>
     *
     * <code>repeated .a2a.v1.Task tasks = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public io.a2a.grpc.Task.Builder addTasksBuilder(
        int index) {
      return internalGetTasksFieldBuilder().addBuilder(
          index, io.a2a.grpc.Task.getDefaultInstance());
    }
    /**
     * <pre>
     * Array of tasks matching the specified criteria.
     * </pre>
     *
     * <code>repeated .a2a.v1.Task tasks = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public java.util.List<io.a2a.grpc.Task.Builder> 
         getTasksBuilderList() {
      return internalGetTasksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.a2a.grpc.Task, io.a2a.grpc.Task.Builder, io.a2a.grpc.TaskOrBuilder> 
        internalGetTasksFieldBuilder() {
      if (tasksBuilder_ == null) {
        tasksBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.a2a.grpc.Task, io.a2a.grpc.Task.Builder, io.a2a.grpc.TaskOrBuilder>(
                tasks_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        tasks_ = null;
      }
      return tasksBuilder_;
    }

    private java.lang.Object nextPageToken_ = "";
    /**
     * <pre>
     * Token for retrieving the next page. Empty string if no more results.
     * </pre>
     *
     * <code>string next_page_token = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The nextPageToken.
     */
    public java.lang.String getNextPageToken() {
      java.lang.Object ref = nextPageToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nextPageToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Token for retrieving the next page. Empty string if no more results.
     * </pre>
     *
     * <code>string next_page_token = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for nextPageToken.
     */
    public com.google.protobuf.ByteString
        getNextPageTokenBytes() {
      java.lang.Object ref = nextPageToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nextPageToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Token for retrieving the next page. Empty string if no more results.
     * </pre>
     *
     * <code>string next_page_token = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The nextPageToken to set.
     * @return This builder for chaining.
     */
    public Builder setNextPageToken(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nextPageToken_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Token for retrieving the next page. Empty string if no more results.
     * </pre>
     *
     * <code>string next_page_token = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearNextPageToken() {
      nextPageToken_ = getDefaultInstance().getNextPageToken();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Token for retrieving the next page. Empty string if no more results.
     * </pre>
     *
     * <code>string next_page_token = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for nextPageToken to set.
     * @return This builder for chaining.
     */
    public Builder setNextPageTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nextPageToken_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int pageSize_ ;
    /**
     * <pre>
     * The size of page requested.
     * </pre>
     *
     * <code>int32 page_size = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The pageSize.
     */
    @java.lang.Override
    public int getPageSize() {
      return pageSize_;
    }
    /**
     * <pre>
     * The size of page requested.
     * </pre>
     *
     * <code>int32 page_size = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The pageSize to set.
     * @return This builder for chaining.
     */
    public Builder setPageSize(int value) {

      pageSize_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The size of page requested.
     * </pre>
     *
     * <code>int32 page_size = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearPageSize() {
      bitField0_ = (bitField0_ & ~0x00000004);
      pageSize_ = 0;
      onChanged();
      return this;
    }

    private int totalSize_ ;
    /**
     * <pre>
     * Total number of tasks available (before pagination).
     * </pre>
     *
     * <code>int32 total_size = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The totalSize.
     */
    @java.lang.Override
    public int getTotalSize() {
      return totalSize_;
    }
    /**
     * <pre>
     * Total number of tasks available (before pagination).
     * </pre>
     *
     * <code>int32 total_size = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The totalSize to set.
     * @return This builder for chaining.
     */
    public Builder setTotalSize(int value) {

      totalSize_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Total number of tasks available (before pagination).
     * </pre>
     *
     * <code>int32 total_size = 4 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalSize() {
      bitField0_ = (bitField0_ & ~0x00000008);
      totalSize_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:a2a.v1.ListTasksResponse)
  }

  // @@protoc_insertion_point(class_scope:a2a.v1.ListTasksResponse)
  private static final io.a2a.grpc.ListTasksResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.a2a.grpc.ListTasksResponse();
  }

  public static io.a2a.grpc.ListTasksResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListTasksResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListTasksResponse>() {
    @java.lang.Override
    public ListTasksResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListTasksResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListTasksResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.a2a.grpc.ListTasksResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

