// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface MutualTlsSecuritySchemeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.MutualTlsSecurityScheme)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * An optional description for the security scheme.
   * </pre>
   *
   * <code>string description = 1;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * An optional description for the security scheme.
   * </pre>
   *
   * <code>string description = 1;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
