// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface OpenIdConnectSecuritySchemeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.OpenIdConnectSecurityScheme)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * An optional description for the security scheme.
   * </pre>
   *
   * <code>string description = 1;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * An optional description for the security scheme.
   * </pre>
   *
   * <code>string description = 1;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * The OpenID Connect Discovery URL for the OIDC provider's metadata.
   * See: https://openid.net/specs/openid-connect-discovery-1_0.html
   * </pre>
   *
   * <code>string open_id_connect_url = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The openIdConnectUrl.
   */
  java.lang.String getOpenIdConnectUrl();
  /**
   * <pre>
   * The OpenID Connect Discovery URL for the OIDC provider's metadata.
   * See: https://openid.net/specs/openid-connect-discovery-1_0.html
   * </pre>
   *
   * <code>string open_id_connect_url = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for openIdConnectUrl.
   */
  com.google.protobuf.ByteString
      getOpenIdConnectUrlBytes();
}
