// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface PartOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.Part)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The string content of the text part.
   * </pre>
   *
   * <code>string text = 1;</code>
   * @return Whether the text field is set.
   */
  boolean hasText();
  /**
   * <pre>
   * The string content of the text part.
   * </pre>
   *
   * <code>string text = 1;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <pre>
   * The string content of the text part.
   * </pre>
   *
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <pre>
   * The file content, represented as either a URI or as base64-encoded bytes.
   * </pre>
   *
   * <code>.a2a.v1.FilePart file = 2;</code>
   * @return Whether the file field is set.
   */
  boolean hasFile();
  /**
   * <pre>
   * The file content, represented as either a URI or as base64-encoded bytes.
   * </pre>
   *
   * <code>.a2a.v1.FilePart file = 2;</code>
   * @return The file.
   */
  io.a2a.grpc.FilePart getFile();
  /**
   * <pre>
   * The file content, represented as either a URI or as base64-encoded bytes.
   * </pre>
   *
   * <code>.a2a.v1.FilePart file = 2;</code>
   */
  io.a2a.grpc.FilePartOrBuilder getFileOrBuilder();

  /**
   * <pre>
   * The structured data content.
   * </pre>
   *
   * <code>.a2a.v1.DataPart data = 3;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <pre>
   * The structured data content.
   * </pre>
   *
   * <code>.a2a.v1.DataPart data = 3;</code>
   * @return The data.
   */
  io.a2a.grpc.DataPart getData();
  /**
   * <pre>
   * The structured data content.
   * </pre>
   *
   * <code>.a2a.v1.DataPart data = 3;</code>
   */
  io.a2a.grpc.DataPartOrBuilder getDataOrBuilder();

  /**
   * <pre>
   * Optional metadata associated with this part.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 4;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * Optional metadata associated with this part.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 4;</code>
   * @return The metadata.
   */
  com.google.protobuf.Struct getMetadata();
  /**
   * <pre>
   * Optional metadata associated with this part.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 4;</code>
   */
  com.google.protobuf.StructOrBuilder getMetadataOrBuilder();

  io.a2a.grpc.Part.PartCase getPartCase();
}
