// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface SendMessageConfigurationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lf.a2a.v1.SendMessageConfiguration)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A list of media types the client is prepared to accept for response parts.
   * Agents SHOULD use this to tailor their output.
   * </pre>
   *
   * <code>repeated string accepted_output_modes = 1;</code>
   * @return A list containing the acceptedOutputModes.
   */
  java.util.List<java.lang.String>
      getAcceptedOutputModesList();
  /**
   * <pre>
   * A list of media types the client is prepared to accept for response parts.
   * Agents SHOULD use this to tailor their output.
   * </pre>
   *
   * <code>repeated string accepted_output_modes = 1;</code>
   * @return The count of acceptedOutputModes.
   */
  int getAcceptedOutputModesCount();
  /**
   * <pre>
   * A list of media types the client is prepared to accept for response parts.
   * Agents SHOULD use this to tailor their output.
   * </pre>
   *
   * <code>repeated string accepted_output_modes = 1;</code>
   * @param index The index of the element to return.
   * @return The acceptedOutputModes at the given index.
   */
  java.lang.String getAcceptedOutputModes(int index);
  /**
   * <pre>
   * A list of media types the client is prepared to accept for response parts.
   * Agents SHOULD use this to tailor their output.
   * </pre>
   *
   * <code>repeated string accepted_output_modes = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the acceptedOutputModes at the given index.
   */
  com.google.protobuf.ByteString
      getAcceptedOutputModesBytes(int index);

  /**
   * <pre>
   * Configuration for the agent to send push notifications for task updates.
   * Task id should be empty when sending this configuration in a `SendMessage` request.
   * </pre>
   *
   * <code>.lf.a2a.v1.TaskPushNotificationConfig task_push_notification_config = 2;</code>
   * @return Whether the taskPushNotificationConfig field is set.
   */
  boolean hasTaskPushNotificationConfig();
  /**
   * <pre>
   * Configuration for the agent to send push notifications for task updates.
   * Task id should be empty when sending this configuration in a `SendMessage` request.
   * </pre>
   *
   * <code>.lf.a2a.v1.TaskPushNotificationConfig task_push_notification_config = 2;</code>
   * @return The taskPushNotificationConfig.
   */
  io.a2a.grpc.TaskPushNotificationConfig getTaskPushNotificationConfig();
  /**
   * <pre>
   * Configuration for the agent to send push notifications for task updates.
   * Task id should be empty when sending this configuration in a `SendMessage` request.
   * </pre>
   *
   * <code>.lf.a2a.v1.TaskPushNotificationConfig task_push_notification_config = 2;</code>
   */
  io.a2a.grpc.TaskPushNotificationConfigOrBuilder getTaskPushNotificationConfigOrBuilder();

  /**
   * <pre>
   * The maximum number of most recent messages from the task's history to retrieve in
   * the response. An unset value means the client does not impose any limit. A
   * value of zero is a request to not include any messages. The server MUST NOT
   * return more messages than the provided value, but MAY apply a lower limit.
   * </pre>
   *
   * <code>optional int32 history_length = 3;</code>
   * @return Whether the historyLength field is set.
   */
  boolean hasHistoryLength();
  /**
   * <pre>
   * The maximum number of most recent messages from the task's history to retrieve in
   * the response. An unset value means the client does not impose any limit. A
   * value of zero is a request to not include any messages. The server MUST NOT
   * return more messages than the provided value, but MAY apply a lower limit.
   * </pre>
   *
   * <code>optional int32 history_length = 3;</code>
   * @return The historyLength.
   */
  int getHistoryLength();

  /**
   * <pre>
   * If `true`, the operation returns immediately after creating the task,
   * even if processing is still in progress.
   * If `false` (default), the operation MUST wait until the task reaches a
   * terminal (`COMPLETED`, `FAILED`, `CANCELED`, `REJECTED`) or interrupted
   * (`INPUT_REQUIRED`, `AUTH_REQUIRED`) state before returning.
   * </pre>
   *
   * <code>bool return_immediately = 4;</code>
   * @return The returnImmediately.
   */
  boolean getReturnImmediately();
}
