// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface SendMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.SendMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional tenant, provided as a path parameter.
   * </pre>
   *
   * <code>string tenant = 4;</code>
   * @return The tenant.
   */
  java.lang.String getTenant();
  /**
   * <pre>
   * Optional tenant, provided as a path parameter.
   * </pre>
   *
   * <code>string tenant = 4;</code>
   * @return The bytes for tenant.
   */
  com.google.protobuf.ByteString
      getTenantBytes();

  /**
   * <pre>
   * The message to send to the agent.
   * </pre>
   *
   * <code>.a2a.v1.Message message = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <pre>
   * The message to send to the agent.
   * </pre>
   *
   * <code>.a2a.v1.Message message = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The message.
   */
  io.a2a.grpc.Message getMessage();
  /**
   * <pre>
   * The message to send to the agent.
   * </pre>
   *
   * <code>.a2a.v1.Message message = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  io.a2a.grpc.MessageOrBuilder getMessageOrBuilder();

  /**
   * <pre>
   * Configuration for the send request.
   * </pre>
   *
   * <code>.a2a.v1.SendMessageConfiguration configuration = 2;</code>
   * @return Whether the configuration field is set.
   */
  boolean hasConfiguration();
  /**
   * <pre>
   * Configuration for the send request.
   * </pre>
   *
   * <code>.a2a.v1.SendMessageConfiguration configuration = 2;</code>
   * @return The configuration.
   */
  io.a2a.grpc.SendMessageConfiguration getConfiguration();
  /**
   * <pre>
   * Configuration for the send request.
   * </pre>
   *
   * <code>.a2a.v1.SendMessageConfiguration configuration = 2;</code>
   */
  io.a2a.grpc.SendMessageConfigurationOrBuilder getConfigurationOrBuilder();

  /**
   * <pre>
   * A flexible key-value map for passing additional context or parameters.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 3;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * A flexible key-value map for passing additional context or parameters.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 3;</code>
   * @return The metadata.
   */
  com.google.protobuf.Struct getMetadata();
  /**
   * <pre>
   * A flexible key-value map for passing additional context or parameters.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 3;</code>
   */
  com.google.protobuf.StructOrBuilder getMetadataOrBuilder();
}
