// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface SetTaskPushNotificationConfigRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.SetTaskPushNotificationConfigRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional tenant, provided as a path parameter.
   * </pre>
   *
   * <code>string tenant = 4;</code>
   * @return The tenant.
   */
  java.lang.String getTenant();
  /**
   * <pre>
   * Optional tenant, provided as a path parameter.
   * </pre>
   *
   * <code>string tenant = 4;</code>
   * @return The bytes for tenant.
   */
  com.google.protobuf.ByteString
      getTenantBytes();

  /**
   * <pre>
   * The parent task resource for this config.
   * Format: tasks/{task_id}
   * </pre>
   *
   * <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The parent.
   */
  java.lang.String getParent();
  /**
   * <pre>
   * The parent task resource for this config.
   * Format: tasks/{task_id}
   * </pre>
   *
   * <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for parent.
   */
  com.google.protobuf.ByteString
      getParentBytes();

  /**
   * <pre>
   * The ID for the new config.
   * </pre>
   *
   * <code>string config_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The configId.
   */
  java.lang.String getConfigId();
  /**
   * <pre>
   * The ID for the new config.
   * </pre>
   *
   * <code>string config_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for configId.
   */
  com.google.protobuf.ByteString
      getConfigIdBytes();

  /**
   * <pre>
   * The configuration to create.
   * </pre>
   *
   * <code>.a2a.v1.TaskPushNotificationConfig config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the config field is set.
   */
  boolean hasConfig();
  /**
   * <pre>
   * The configuration to create.
   * </pre>
   *
   * <code>.a2a.v1.TaskPushNotificationConfig config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The config.
   */
  io.a2a.grpc.TaskPushNotificationConfig getConfig();
  /**
   * <pre>
   * The configuration to create.
   * </pre>
   *
   * <code>.a2a.v1.TaskPushNotificationConfig config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  io.a2a.grpc.TaskPushNotificationConfigOrBuilder getConfigOrBuilder();
}
