// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface SubscribeToTaskRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.SubscribeToTaskRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional tenant, provided as a path parameter.
   * </pre>
   *
   * <code>string tenant = 2;</code>
   * @return The tenant.
   */
  java.lang.String getTenant();
  /**
   * <pre>
   * Optional tenant, provided as a path parameter.
   * </pre>
   *
   * <code>string tenant = 2;</code>
   * @return The bytes for tenant.
   */
  com.google.protobuf.ByteString
      getTenantBytes();

  /**
   * <pre>
   * The resource name of the task to subscribe to.
   * Format: tasks/{task_id}
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The resource name of the task to subscribe to.
   * Format: tasks/{task_id}
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
