// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface TaskStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.TaskStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The current state of this task.
   * </pre>
   *
   * <code>.a2a.v1.TaskState state = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <pre>
   * The current state of this task.
   * </pre>
   *
   * <code>.a2a.v1.TaskState state = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The state.
   */
  io.a2a.grpc.TaskState getState();

  /**
   * <pre>
   * A message associated with the status.
   * </pre>
   *
   * <code>.a2a.v1.Message message = 2;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <pre>
   * A message associated with the status.
   * </pre>
   *
   * <code>.a2a.v1.Message message = 2;</code>
   * @return The message.
   */
  io.a2a.grpc.Message getMessage();
  /**
   * <pre>
   * A message associated with the status.
   * </pre>
   *
   * <code>.a2a.v1.Message message = 2;</code>
   */
  io.a2a.grpc.MessageOrBuilder getMessageOrBuilder();

  /**
   * <pre>
   * ISO 8601 Timestamp when the status was recorded.
   * Example: "2023-10-27T10:00:00Z"
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 3;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <pre>
   * ISO 8601 Timestamp when the status was recorded.
   * Example: "2023-10-27T10:00:00Z"
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 3;</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <pre>
   * ISO 8601 Timestamp when the status was recorded.
   * Example: "2023-10-27T10:00:00Z"
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();
}
