// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface TaskArtifactUpdateEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.TaskArtifactUpdateEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The id of the task for this artifact.
   * </pre>
   *
   * <code>string task_id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <pre>
   * The id of the task for this artifact.
   * </pre>
   *
   * <code>string task_id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <pre>
   * The id of the context that this task belongs to.
   * </pre>
   *
   * <code>string context_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The contextId.
   */
  java.lang.String getContextId();
  /**
   * <pre>
   * The id of the context that this task belongs to.
   * </pre>
   *
   * <code>string context_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for contextId.
   */
  com.google.protobuf.ByteString
      getContextIdBytes();

  /**
   * <pre>
   * The artifact that was generated or updated.
   * </pre>
   *
   * <code>.a2a.v1.Artifact artifact = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the artifact field is set.
   */
  boolean hasArtifact();
  /**
   * <pre>
   * The artifact that was generated or updated.
   * </pre>
   *
   * <code>.a2a.v1.Artifact artifact = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The artifact.
   */
  io.a2a.grpc.Artifact getArtifact();
  /**
   * <pre>
   * The artifact that was generated or updated.
   * </pre>
   *
   * <code>.a2a.v1.Artifact artifact = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  io.a2a.grpc.ArtifactOrBuilder getArtifactOrBuilder();

  /**
   * <pre>
   * If true, the content of this artifact should be appended to a previously
   * sent artifact with the same ID.
   * </pre>
   *
   * <code>bool append = 4;</code>
   * @return The append.
   */
  boolean getAppend();

  /**
   * <pre>
   * If true, this is the final chunk of the artifact.
   * </pre>
   *
   * <code>bool last_chunk = 5;</code>
   * @return The lastChunk.
   */
  boolean getLastChunk();

  /**
   * <pre>
   * Optional metadata associated with the artifact update.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 6;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * Optional metadata associated with the artifact update.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 6;</code>
   * @return The metadata.
   */
  com.google.protobuf.Struct getMetadata();
  /**
   * <pre>
   * Optional metadata associated with the artifact update.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 6;</code>
   */
  com.google.protobuf.StructOrBuilder getMetadataOrBuilder();
}
