# A workflow that can be called by other workflows to run the TCK against a System Under Test (SUT).
# It expects an artifact named `sut-artifact` to be downloaded, which contains:
#  - A directory structure with what is needed to run the server with the A2A SDK enabled.
#  - A `start-sut.sh` script that starts the SUT server, and is able to work on the above directory structure.
#
# The inputs to this workflow are:
#  - `tag`: The tag of the TCK to run against the SUT.
#   - `sut-url`: The URL of the SUT to run the TCK against. This will be used to check the server has started.
# Then there are further optional inputs, each of which enabled a particular language setup step, so we can run the
# SUT on its preferred language:
#   - `java-version`: The Java version to use for the TCK run. If not provided, it will not set up Java.
#
# Example usage in a workflow:
#
# name: Build SUT
# jobs:
#  prepare-sut:
#    name: Preparing SUT
#    runs-on: ubuntu-latest
#    outputs:
#      # GitHub Actions don't allow use of env in the run-tck job calling the reusable workflow. Use an output instead
#      tck_version: ${{ steps.set_vars.outputs.version }}
#    steps:
#      - name: Set TCK Version Output
#        id: set_vars
#        run: echo "version=${{ env.TCK_VERSION }}" >> $GITHUB_OUTPUT
#      # Steps to checkout the server implementation and build it with its language- name: Checkout a2a-java
#        uses: actions/checkout@v4
#      - name: Create artifact directory
#        run: |
#          mkdir artifact-dir
#          # Copy server files to artifact-dir
#          cp .github/workflows/tck/start-sut.sh artifact-dir
#          echo
#      - name: Upload SUT artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          # The name of the artifact needs to be `sut-artifact` so that the reusable workflow can find it
#          name: sut-artifact
#          path: artifact-dir/
#
#  # Use the reusable workflow to run the TCK against the SUT
#  run-tck:
#    name: Running TCK
#    uses: a2aproject/a2a-tck/.github/workflows/reusable-tck-runner.yml@main
#    needs: prepare-sut
#    with:
#      tag: ${{ needs.prepare-sut.outputs.tck_version }}
#      # `java-version` indicates that the SUT is a Java server, so we need to install Java.
#      java-version: 17
#      sut-url: http://localhost:9999/.well-known/agent.json
#


name: Run TCK
on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag to run the TCK against'
        required: true
        type: string
      java-version:
        description: 'Java version to use for the TCK run'
        required: false
        type: string
      # TODO xxx-version input parameters for other languages as needed. The presence of each
      #  parameter will determine if the setup-xxxx step is run
      sut-url:
        description: 'The URL of the System Under Test (SUT) to run the TCK against. This will be used to check the server has started'
        required: true
        type: string
env:
  # Tells uv to not need a venv, and instead use system
  UV_SYSTEM_PYTHON: 1

jobs:
  tck-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Download the SUT artifact
        uses: actions/download-artifact@v4
        with:
          name: sut-artifact
          path: ~/sut

      - name: Start SUT
        run: |
          # Start the SUT server in the background
          cd ~/sut
          echo "Current directory: $(pwd)"
          ls -al
          if [ ! -f start-sut.sh ]; then
            echo "start-sut.sh not found in the sut/ directory."
            exit 1
          fi
          chmod 775 start-sut.sh
          
          ./start-sut.sh &

      - name: Checkout TCK
        uses: actions/checkout@v4
        with:
          repository: 'a2aproject/a2a-tck'
          ref: ${{ inputs.tag }}
          path: tck

      - name: Set up JDK
        uses: actions/setup-java@v4
        if: ${{ inputs.java-version != '' }}
        with:
          java-version: '17'
          distribution: 'temurin'

      # TODO set up other languages as needed

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "tck/pyproject.toml"

      - name: Install uv and Python dependencies
        run: |
          pip install uv
          uv pip install -e .
        working-directory: tck

      - name: Wait for SUT to start
        run: |
          URL="${{ inputs.sut-url }}"
          EXPECTED_STATUS=200
          TIMEOUT=120
          RETRY_INTERVAL=2
          START_TIME=$(date +%s)

          while true; do
            # Calculate elapsed time
            CURRENT_TIME=$(date +%s)
            ELAPSED_TIME=$((CURRENT_TIME - START_TIME))

            # Check for timeout
            if [ "$ELAPSED_TIME" -ge "$TIMEOUT" ]; then
                echo "❌ Timeout: Server did not respond with status $EXPECTED_STATUS within $TIMEOUT seconds."
                exit 1
            fi

            # Get HTTP status code. || true is to reporting a failure to connect as an error
            HTTP_STATUS=$(curl --output /dev/null --silent --write-out "%{http_code}" "$URL") || true
            echo "STATUS: ${HTTP_STATUS}"

            # Check if we got the correct status code
            if [ "$HTTP_STATUS" -eq "$EXPECTED_STATUS" ]; then
                echo "✅ Server is up! Received status $HTTP_STATUS after $ELAPSED_TIME seconds."
                break;
            fi

            # Wait before retrying
            echo "⏳ Server not ready (status: $HTTP_STATUS). Retrying in $RETRY_INTERVAL seconds..."
            sleep "$RETRY_INTERVAL"
          done

      - name: Run TCK
        run: |
          ./run_tck.py --sut-url http://localhost:9999 --category all --compliance-report report.json
        working-directory: tck
